[package]
name = "boxology-generator"
version = "0.0.0"
edition.workspace = true
publish = false

[dependencies]
boxology-generator-model = { version = "=0.0.0", path = "../boxology-generator-model" }
prettyplease = "=0.3.0"
syn = { version = "=3.0.0", default-features = false, features = ["full", "parsing"] }

[dev-dependencies]
boxology-contract = { version = "=0.0.0", path = "../boxology-contract" }
