[workspace]
resolver = "3"
members = [
    "crates/boxology-contract",
    "crates/boxology-contract-syntax",
    "crates/boxology-generator-model",
    "crates/boxology-http",
    "crates/boxology-runtime",
    "crates/fixtures/fixture-tests",
    "crates/fixtures/generated-style-fmt",
    "crates/fixtures/hello/generated/contract",
    "crates/fixtures/hello/implementation",
    "crates/xtask",
]

[workspace.package]
edition = "2024"
