use boxology_contract::BoxId;
use boxology_generator::{OUTPUTS, generate};
use boxology_generator_model::{
    ContractDeclaration, ContractDeclarationShape, ContractDeclarationSyntax, ContractFields,
    GenerationRequest, Manifest, ParsedRustInputs,
};
use serde_json::Value;
use std::{collections::BTreeSet, fs, path::Path};

const FIXTURE_OUTPUTS: [&str; 4] = [
    "generated/adapter/adapter.rs",
    "generated/contract/Cargo.toml",
    "generated/contract/src/lib.rs",
    "generated/schema.json",
];
const RUST_GENERATOR_HEADER: &str = "// Generated by boxology-generator ";
const PROVENANCE_TOKEN: &str = "@PROVENANCE@";

struct Fixture {
    name: &'static str,
    manifest: &'static [u8],
    implementation: &'static [u8],
    contract: &'static [u8],
    import_schema: Option<(&'static str, &'static str, &'static [u8])>,
    goldens: [(&'static str, &'static [u8]); 4],
}

macro_rules! golden {
    ($name:literal, $path:literal) => {
        (
            $path,
            include_bytes!(concat!("../../fixtures/", $name, "/", $path)),
        )
    };
}

macro_rules! fixture {
    ($name:literal, $import_schema:expr) => {
        Fixture {
            name: $name,
            manifest: include_bytes!(concat!("../../fixtures/", $name, "/boxology.toml")),
            implementation: include_bytes!(concat!(
                "../../fixtures/",
                $name,
                "/implementation/src/lib.rs"
            )),
            contract: include_bytes!(concat!(
                "../../fixtures/",
                $name,
                "/implementation/src/contract.rs"
            )),
            import_schema: $import_schema,
            goldens: [
                golden!($name, "generated/adapter/adapter.rs"),
                golden!($name, "generated/contract/Cargo.toml"),
                golden!($name, "generated/contract/src/lib.rs"),
                golden!($name, "generated/schema.json"),
            ],
        }
    };
}

const HELLO_SCHEMA: &[u8] = include_bytes!("../../fixtures/hello/generated/schema.json");
static FIXTURES: [Fixture; 3] = [
    fixture!(
        "greeter",
        Some(("hello", "hello/generated/schema.json", HELLO_SCHEMA))
    ),
    fixture!("hello", None),
    fixture!("ping", None),
];

fn rust_string_literal(path: &Path) -> String {
    format!("{:?}", path.to_string_lossy())
}

fn field_projection(fields: &ContractFields<'_>) -> String {
    let fields = match fields {
        ContractFields::Named(fields) | ContractFields::Unnamed(fields) => fields,
        ContractFields::Unit => return "unit".into(),
    };
    format!(
        "{:?}",
        fields
            .iter()
            .map(|field| (
                field.ordinal(),
                field.identity().map(|identity| identity.name()),
                field.metadata().deprecation().map(|value| value.note()),
            ))
            .collect::<Vec<_>>()
    )
}

fn shape_projection(declaration: &ContractDeclaration<'_>) -> String {
    let deprecated = declaration
        .metadata()
        .deprecation()
        .map(|value| value.note());
    match declaration.shape() {
        ContractDeclarationShape::Struct(fields) => format!(
            "{} struct deprecated={deprecated:?} fields={}",
            declaration.lifted_name(),
            field_projection(fields)
        ),
        ContractDeclarationShape::Enum(variants) => format!(
            "{} enum deprecated={deprecated:?} variants={:?}",
            declaration.lifted_name(),
            variants
                .iter()
                .map(|variant| (
                    variant.ordinal(),
                    variant.identity().name(),
                    variant.metadata().deprecation().map(|value| value.note()),
                    field_projection(variant.fields()),
                ))
                .collect::<Vec<_>>()
        ),
    }
}

fn docs_projection(declaration: &ContractDeclaration<'_>) -> String {
    let fields = |fields: &ContractFields<'_>| match fields {
        ContractFields::Named(fields) | ContractFields::Unnamed(fields) => format!(
            "{:?}",
            fields
                .iter()
                .map(|field| field.metadata().docs())
                .collect::<Vec<_>>()
        ),
        ContractFields::Unit => "unit".into(),
    };
    match declaration.shape() {
        ContractDeclarationShape::Struct(shape) => format!(
            "{} struct docs={:?} fields={}",
            declaration.lifted_name(),
            declaration.metadata().docs(),
            fields(shape)
        ),
        ContractDeclarationShape::Enum(variants) => format!(
            "{} enum docs={:?} variants={:?}",
            declaration.lifted_name(),
            declaration.metadata().docs(),
            variants
                .iter()
                .map(|variant| (variant.metadata().docs(), fields(variant.fields())))
                .collect::<Vec<_>>()
        ),
    }
}

fn fixture_root() -> std::path::PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../fixtures")
}

fn require_real_directory(path: &Path) -> Result<(), String> {
    let kind = fs::symlink_metadata(path)
        .map_err(|error| format!("inspect directory {}: {error}", path.display()))?
        .file_type();
    if kind.is_dir() {
        Ok(())
    } else {
        Err(format!("not a real directory: {}", path.display()))
    }
}

fn discover_fixture_schema_owners_at(root: &Path) -> Result<Vec<String>, String> {
    require_real_directory(root)?;
    let mut owners = Vec::new();
    for entry in fs::read_dir(root).map_err(|error| format!("read fixture root: {error}"))? {
        let entry = entry.map_err(|error| format!("read fixture entry: {error}"))?;
        let kind = fs::symlink_metadata(entry.path())
            .map_err(|error| format!("inspect fixture entry: {error}"))?
            .file_type();
        if kind.is_symlink() {
            return Err(format!("fixture root symlink: {}", entry.path().display()));
        }
        if !kind.is_dir() {
            continue;
        }
        let name = entry
            .file_name()
            .into_string()
            .map_err(|_| "fixture directory name is not UTF-8".to_owned())?;
        let schema = entry.path().join("generated/schema.json");
        match fs::symlink_metadata(&schema) {
            Ok(metadata) if metadata.file_type().is_file() => owners.push(name),
            Ok(_) => {
                return Err(format!(
                    "fixture schema owner is not a regular file: {}",
                    schema.display()
                ));
            }
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
            Err(error) => return Err(format!("inspect fixture schema: {error}")),
        }
    }
    owners.sort_by(|left, right| left.as_bytes().cmp(right.as_bytes()));
    Ok(owners)
}

fn discover_fixture_schema_owners() -> Result<Vec<String>, String> {
    discover_fixture_schema_owners_at(&fixture_root())
}

fn validate_fixture_owners(registry: &[&str], discovered: &[&str]) -> Result<(), String> {
    if registry
        .windows(2)
        .any(|owners| owners[0].as_bytes() >= owners[1].as_bytes())
    {
        return Err("fixture registry owners must be unique and sorted".into());
    }
    if discovered
        .windows(2)
        .any(|owners| owners[0].as_bytes() >= owners[1].as_bytes())
    {
        return Err("discovered fixture owners must be unique and sorted".into());
    }
    if let Some(owner) = discovered.iter().find(|owner| !registry.contains(owner)) {
        return Err(format!("fixture schema owner is unmapped: {owner}"));
    }
    if let Some(owner) = registry.iter().find(|owner| !discovered.contains(owner)) {
        return Err(format!("fixture registry owner is omitted: {owner}"));
    }
    Ok(())
}

fn checked_in_inventory(name: &str) -> Result<Vec<String>, String> {
    fn visit(root: &Path, directory: &Path, files: &mut Vec<String>) -> Result<(), String> {
        for entry in
            fs::read_dir(directory).map_err(|error| format!("read generated directory: {error}"))?
        {
            let entry = entry.map_err(|error| format!("read generated entry: {error}"))?;
            let path = entry.path();
            let kind = fs::symlink_metadata(&path)
                .map_err(|error| format!("inspect generated entry: {error}"))?;
            let kind = kind.file_type();
            if kind.is_dir() {
                visit(root, &path, files)?;
            } else if kind.is_file() {
                let relative = path
                    .strip_prefix(root)
                    .map_err(|error| format!("strip generated path: {error}"))?
                    .to_str()
                    .ok_or("generated path is not UTF-8")?
                    .replace('\\', "/");
                files.push(relative);
            } else {
                return Err(format!("unsupported generated entry: {}", path.display()));
            }
        }
        Ok(())
    }

    let root = fixture_root().join(name);
    let generated = root.join("generated");
    require_real_directory(&root)?;
    require_real_directory(&generated)?;
    let mut files = Vec::new();
    visit(&root, &generated, &mut files)?;
    files.sort_by(|left, right| left.as_bytes().cmp(right.as_bytes()));
    Ok(files)
}

fn fixture_request(fixture: &Fixture) -> Result<GenerationRequest, String> {
    let mut inputs = vec![
        ("boxology.toml".into(), fixture.manifest.to_vec()),
        (
            "implementation/src/lib.rs".into(),
            fixture.implementation.to_vec(),
        ),
        (
            "implementation/src/contract.rs".into(),
            fixture.contract.to_vec(),
        ),
    ];
    let mut imports = Vec::new();
    if let Some((package, path, schema)) = fixture.import_schema {
        inputs.push((path.into(), schema.to_vec()));
        imports.push((
            BoxId::new(package)
                .map_err(|error| format!("{} import id is invalid: {error}", fixture.name))?,
            path.into(),
        ));
    }
    GenerationRequest::new(
        BoxId::new(fixture.name)
            .map_err(|error| format!("{} fixture id is invalid: {error}", fixture.name))?,
        "implementation/src/lib.rs".into(),
        inputs,
        imports,
        OUTPUTS.iter().map(|path| (*path).to_owned()).collect(),
    )
    .map_err(|error| format!("{} fixture request failed: {error}", fixture.name))
}

fn generated_bytes<'a>(
    tree: &'a boxology_generator::GeneratedTree,
    path: &str,
) -> Result<&'a [u8], String> {
    tree.files()
        .iter()
        .find(|file| file.path() == path)
        .map(|file| file.bytes())
        .ok_or_else(|| format!("generated output is missing: {path}"))
}

fn golden_bytes(fixture: &Fixture, path: &str) -> Result<&'static [u8], String> {
    fixture
        .goldens
        .iter()
        .find(|(golden, _)| *golden == path)
        .map(|(_, bytes)| *bytes)
        .ok_or_else(|| format!("{} golden is missing: {path}", fixture.name))
}

fn normalize_rust(bytes: &[u8]) -> Result<Vec<u8>, String> {
    let text =
        std::str::from_utf8(bytes).map_err(|error| format!("Rust output is not UTF-8: {error}"))?;
    let (header, body) = text
        .split_once('\n')
        .ok_or("Rust output has no first LF line")?;
    if !header.starts_with(RUST_GENERATOR_HEADER)
        || text
            .lines()
            .filter(|line| line.starts_with(RUST_GENERATOR_HEADER))
            .count()
            != 1
    {
        return Err("invalid Rust generator header placement or count".into());
    }
    Ok(format!("// Generated by boxology-generator {PROVENANCE_TOKEN}\n{body}").into_bytes())
}

fn json_whitespace(bytes: &[u8], offset: &mut usize) {
    while bytes
        .get(*offset)
        .is_some_and(|byte| matches!(byte, b' ' | b'\n' | b'\r' | b'\t'))
    {
        *offset += 1;
    }
}

fn json_string(bytes: &[u8], offset: &mut usize) -> Result<String, String> {
    let start = *offset;
    if bytes.get(*offset) != Some(&b'"') {
        return Err("schema JSON object key is not a string".into());
    }
    *offset += 1;
    let mut escaped = false;
    while let Some(byte) = bytes.get(*offset).copied() {
        *offset += 1;
        if escaped {
            escaped = false;
        } else if byte == b'\\' {
            escaped = true;
        } else if byte == b'"' {
            return serde_json::from_slice(&bytes[start..*offset])
                .map_err(|error| format!("schema JSON string is invalid: {error}"));
        }
    }
    Err("schema JSON string is unterminated".into())
}

fn scan_json_value(bytes: &[u8], offset: &mut usize) -> Result<(), String> {
    json_whitespace(bytes, offset);
    match bytes.get(*offset) {
        Some(b'{') => {
            *offset += 1;
            let mut keys = BTreeSet::new();
            loop {
                json_whitespace(bytes, offset);
                if bytes.get(*offset) == Some(&b'}') {
                    *offset += 1;
                    return Ok(());
                }
                let key = json_string(bytes, offset)?;
                if !keys.insert(key.clone()) {
                    return Err(format!("schema JSON object has duplicate key: {key}"));
                }
                json_whitespace(bytes, offset);
                if bytes.get(*offset) != Some(&b':') {
                    return Err("schema JSON object key has no colon".into());
                }
                *offset += 1;
                scan_json_value(bytes, offset)?;
                json_whitespace(bytes, offset);
                match bytes.get(*offset) {
                    Some(b',') => *offset += 1,
                    Some(b'}') => {
                        *offset += 1;
                        return Ok(());
                    }
                    _ => return Err("schema JSON object has no comma or closing brace".into()),
                }
            }
        }
        Some(b'[') => {
            *offset += 1;
            loop {
                json_whitespace(bytes, offset);
                if bytes.get(*offset) == Some(&b']') {
                    *offset += 1;
                    return Ok(());
                }
                scan_json_value(bytes, offset)?;
                json_whitespace(bytes, offset);
                match bytes.get(*offset) {
                    Some(b',') => *offset += 1,
                    Some(b']') => {
                        *offset += 1;
                        return Ok(());
                    }
                    _ => return Err("schema JSON array has no comma or closing bracket".into()),
                }
            }
        }
        Some(b'"') => json_string(bytes, offset).map(|_| ()),
        Some(_) => {
            let start = *offset;
            while bytes.get(*offset).is_some_and(|byte| {
                !matches!(byte, b' ' | b'\n' | b'\r' | b'\t' | b',' | b']' | b'}')
            }) {
                *offset += 1;
            }
            (*offset != start)
                .then_some(())
                .ok_or_else(|| "schema JSON value is missing".into())
        }
        None => Err("schema JSON value is missing".into()),
    }
}

fn reject_duplicate_json_keys(bytes: &[u8]) -> Result<(), String> {
    let mut offset = 0;
    scan_json_value(bytes, &mut offset)?;
    json_whitespace(bytes, &mut offset);
    (offset == bytes.len())
        .then_some(())
        .ok_or_else(|| "schema JSON has trailing bytes".into())
}

fn sort_json_keys(value: &mut Value) {
    match value {
        Value::Object(object) => {
            let mut entries: Vec<_> = std::mem::take(object).into_iter().collect();
            for (_, value) in &mut entries {
                sort_json_keys(value);
            }
            entries.sort_by(|left, right| left.0.as_bytes().cmp(right.0.as_bytes()));
            *object = entries.into_iter().collect();
        }
        Value::Array(values) => values.iter_mut().for_each(sort_json_keys),
        Value::Null | Value::Bool(_) | Value::Number(_) | Value::String(_) => {}
    }
}

#[derive(Clone, Copy)]
enum SchemaBytes {
    Live,
    Golden,
}

fn normalize_schema(bytes: &[u8], kind: SchemaBytes) -> Result<Vec<u8>, String> {
    reject_duplicate_json_keys(bytes)?;
    let mut document: Value = serde_json::from_slice(bytes)
        .map_err(|error| format!("schema is not valid JSON: {error}"))?;
    let object = document
        .as_object_mut()
        .ok_or("schema root is not a JSON object")?;
    let provenance = object
        .get("provenance")
        .ok_or("schema has no top-level provenance field")?;
    match kind {
        SchemaBytes::Live if !provenance.is_object() => {
            return Err("live schema provenance must be an object".into());
        }
        SchemaBytes::Golden if provenance != &Value::String(PROVENANCE_TOKEN.to_owned()) => {
            return Err("golden schema provenance must be the exact token".into());
        }
        SchemaBytes::Live | SchemaBytes::Golden => {}
    }
    object.insert(
        "provenance".into(),
        Value::String(PROVENANCE_TOKEN.to_owned()),
    );
    sort_json_keys(&mut document);
    let mut normalized = serde_json::to_vec_pretty(&document)
        .map_err(|error| format!("serialize normalized schema: {error}"))?;
    normalized.push(b'\n');
    Ok(normalized)
}

fn compare_fixture_output(
    fixture: &Fixture,
    path: &str,
    actual: &[u8],
    expected: &[u8],
) -> Result<(), String> {
    let equal = if path.ends_with(".rs") {
        normalize_rust(actual)? == normalize_rust(expected)?
    } else if path == "generated/schema.json" {
        normalize_schema(actual, SchemaBytes::Live)?
            == normalize_schema(expected, SchemaBytes::Golden)?
    } else {
        actual == expected
    };
    if equal {
        Ok(())
    } else {
        Err(format!("{} generated output differs: {path}", fixture.name))
    }
}

fn publish_fixture_outputs(
    out: &Path,
    fixture: &Fixture,
    tree: &boxology_generator::GeneratedTree,
) -> Result<(), String> {
    for file in tree.files() {
        let destination = out
            .join("fixture-goldens")
            .join(fixture.name)
            .join(file.path());
        fs::create_dir_all(
            destination
                .parent()
                .ok_or("fixture golden destination has no parent")?,
        )
        .map_err(|error| format!("create fixture golden parent: {error}"))?;
        fs::write(&destination, file.bytes())
            .map_err(|error| format!("write fixture golden {}: {error}", file.path()))?;
    }
    Ok(())
}

fn run_fixture(out: &Path, fixture: &Fixture) -> Result<(), String> {
    let request = fixture_request(fixture)?;
    let generated = generate(request)
        .map_err(|error| format!("{} cold generation failed: {error}", fixture.name))?;
    let generated_paths: Vec<_> = generated.files().iter().map(|file| file.path()).collect();
    if generated_paths.as_slice() != FIXTURE_OUTPUTS {
        return Err(format!(
            "{} generated inventory differs: {generated_paths:?}",
            fixture.name
        ));
    }
    let checked_in = checked_in_inventory(fixture.name)?;
    let checked_in_paths: Vec<_> = checked_in.iter().map(String::as_str).collect();
    if checked_in_paths.as_slice() != FIXTURE_OUTPUTS {
        return Err(format!(
            "{} checked-in inventory differs: {checked_in_paths:?}",
            fixture.name
        ));
    }
    for path in FIXTURE_OUTPUTS {
        compare_fixture_output(
            fixture,
            path,
            generated_bytes(&generated, path)?,
            golden_bytes(fixture, path)?,
        )?;
    }
    publish_fixture_outputs(out, fixture, &generated)
}

fn run_fixture_suite(out: &Path) -> Result<(), String> {
    let registry: Vec<_> = FIXTURES.iter().map(|fixture| fixture.name).collect();
    let discovered = discover_fixture_schema_owners()?;
    let discovered: Vec<_> = discovered.iter().map(String::as_str).collect();
    validate_fixture_owners(&registry, &discovered)?;
    for fixture in &FIXTURES {
        run_fixture(out, fixture)?;
    }
    Ok(())
}

pub(crate) fn run(out: &Path) -> Result<(), String> {
    let id = || BoxId::new("subject-box").expect("fixed id is valid");
    let input = |path: &str, bytes: &[u8]| (path.into(), bytes.to_vec());
    let request = GenerationRequest::new(
        id(),
        "source/custom-entry.rs".into(),
        vec![
            (
                "boxology.toml".into(),
                b"schema = 1\nid = \"subject-box\"\nkind = \"box\"\n".to_vec(),
            ),
            (
                "source/custom-entry.rs".into(),
                b"#[boxology::contract]\nstruct Root;\nmod flat;\nmod inline { #[boxology::contract] struct Inner; mod r#type; }\nfn custom_entry() {}\n".to_vec(),
            ),
            ("source/flat.rs".into(), b"#[boxology::contract]\nenum Flat { A }\n".to_vec()),
            ("source/inline/type.rs".into(), b"#[boxology::contract(error)]\nenum Raw { A }\n".to_vec()),
            ("source/unreachable.rs".into(), b"fn hidden() {}\n".to_vec()),
            ("src/z.rs".into(), b"fn z() {}\n".to_vec()),
            ("src/a.rs".into(), b"struct A;\nfn a() {}\n".to_vec()),
        ],
        vec![],
        vec!["generated/schema.json".into()],
    )
    .map_err(|error| format!("fixed valid request failed: {error}"))?;
    let manifest = Manifest::parse(&request)
        .map_err(|error| format!("fixed valid manifest failed: {error}"))?;
    let rust_inputs = ParsedRustInputs::parse(&request)
        .map_err(|error| format!("fixed valid Rust inputs failed: {error}"))?;
    let rust_modules = rust_inputs
        .resolve_reachable_inputs()
        .map_err(|error| format!("fixed valid module topology failed: {error}"))?
        .iter()
        .map(|input| input.path().as_str())
        .collect::<Vec<_>>()
        .join("\n");
    let declaration_projection = rust_inputs
        .discover_contract_declarations()
        .map_err(|error| format!("fixed contract declarations failed: {error}"))?
        .into_iter()
        .map(|declaration| {
            let kind = match declaration.syntax() {
                ContractDeclarationSyntax::Struct(_) => "struct",
                ContractDeclarationSyntax::Enum(_) => "enum",
            };
            format!(
                "{kind} module={:?} name={} source={} span={:?}",
                declaration.module_path(),
                declaration.lifted_name(),
                declaration.source().as_str(),
                declaration.identifier_span()
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    let collision_request = GenerationRequest::new(
        id(),
        "c.rs".into(),
        vec![
            input("boxology.toml", request.inputs()[0].bytes()),
            input("c.rs", b"#[boxology::contract] struct Clash;\nmod n;\n"),
            input("n.rs", b"#[boxology::contract] enum r#Clash { A }\n"),
        ],
        vec![],
        vec![],
    )
    .map_err(|error| format!("fixed collision request failed: {error}"))?;
    let collision_inputs = ParsedRustInputs::parse(&collision_request)
        .map_err(|error| format!("fixed collision inputs failed: {error}"))?;
    let collision_diagnostics = match collision_inputs.discover_contract_declarations() {
        Ok(_) => return Err("fixed collision unexpectedly succeeded".into()),
        Err(diagnostics) => diagnostics,
    };
    let contracts = |source: &[u8], projection| -> Result<_, String> {
        let evaluate = |reversed| -> Result<_, String> {
            let mut files = vec![
                input("boxology.toml", request.inputs()[0].bytes()),
                input("attributes.rs", source),
            ];
            if reversed {
                files.reverse();
            }
            let case = GenerationRequest::new(id(), "attributes.rs".into(), files, vec![], vec![])
                .map_err(|error| format!("fixed attribute request failed: {error}"))?;
            let parsed = ParsedRustInputs::parse(&case)
                .map_err(|error| format!("fixed attribute inputs failed: {error}"))?;
            Ok(parsed.discover_contract_declarations().map(|declarations| {
                declarations
                    .iter()
                    .map(|declaration| {
                        if projection == 3 {
                            docs_projection(declaration)
                        } else if projection == 2 {
                            shape_projection(declaration)
                        } else if projection == 1 {
                            format!("{}={:?}", declaration.lifted_name(), declaration.role())
                        } else {
                            declaration.lifted_name().to_owned()
                        }
                    })
                    .collect::<Vec<_>>()
                    .join("\n")
            }))
        };
        Ok([evaluate(false)?, evaluate(true)?])
    };
    let valid_attributes = contracts(b"#[doc = \"allowed\"]\n#[deprecated(note = \"later\")]\n#[derive(Debug, Clone, PartialEq)]\n#[boxology::contract]\nstruct Allowed { #[boxology::field] value: u8 }\n", 0)?;
    let invalid_attributes = contracts(b"#[boxology::contract]\n#[PrivateAttribute(secret)]\nstruct Invalid { #[derive(PrivateDerive)] field: u8 }\n", 0)?;
    if valid_attributes[0] != valid_attributes[1] || invalid_attributes[0] != invalid_attributes[1]
    {
        return Err("contract attribute result changed with input order".into());
    }
    let attribute_projection = valid_attributes[0]
        .as_ref()
        .map_err(|error| format!("fixed valid attributes failed: {error}"))?;
    let attribute_diagnostics = invalid_attributes[0]
        .as_ref()
        .expect_err("fixed invalid attributes must fail");
    let valid_roles = contracts(b"#[boxology::contract]\nstruct Value;\n#[boxology::contract]\nenum Choice { A }\n#[boxology::contract(error)]\nenum Fault { A }\n", 1)?;
    let invalid_roles = contracts(b"#[boxology::contract(error)]\nstruct PrivateStruct;\n#[boxology::contract(PrivateMarker)]\nenum PrivateEnum { PrivateVariant }\n", 1)?;
    if valid_roles[0] != valid_roles[1] || invalid_roles[0] != invalid_roles[1] {
        return Err("contract role result changed with input order".into());
    }
    let role_projection = valid_roles[0]
        .as_ref()
        .map_err(|error| format!("fixed valid roles failed: {error}"))?;
    let role_diagnostics = invalid_roles[0]
        .as_ref()
        .expect_err("fixed invalid roles must fail");
    let valid_deprecations = contracts(b"#[deprecated]\n#[boxology::contract]\nstruct Value { #[deprecated(note = \"field\")] field: u8 }\n#[deprecated(note = \"type\")]\n#[boxology::contract]\nenum Event { #[deprecated] Unit, Named { #[deprecated(note = \"variant field\")] value: u8 } }\n", 0)?;
    let invalid_deprecations = contracts(b"#[deprecated(PrivateType)]\n#[boxology::contract]\nstruct Invalid { #[deprecated(note = PrivateField)] field: u8 }\n#[boxology::contract]\nenum InvalidEvent { #[deprecated(PrivateVariant)] Bad { #[deprecated(note = PrivateVariantField)] value: u8 } }\n", 0)?;
    if valid_deprecations[0] != valid_deprecations[1]
        || invalid_deprecations[0] != invalid_deprecations[1]
    {
        return Err("contract deprecation result changed with input order".into());
    }
    let deprecation_projection = valid_deprecations[0]
        .as_ref()
        .map_err(|error| format!("fixed valid deprecations failed: {error}"))?;
    let deprecation_diagnostics = invalid_deprecations[0]
        .as_ref()
        .expect_err("fixed invalid deprecations must fail");
    let shapes = contracts(b"#[deprecated]\n#[boxology::contract]\nstruct Named { #[deprecated(note = \"named\\nfield\")] r#field: &'static [u8; 7] }\n#[deprecated(note = \"tuple\")] #[boxology::contract] struct Tuple(#[deprecated] u8);\n#[boxology::contract] struct Unit;\n#[deprecated(note = \"error\")] #[boxology::contract(error)] enum Event { #[deprecated] r#Unit, #[deprecated(note = \"variant\")] Tuple(#[deprecated] u8), Named { #[deprecated(note = \"value\")] r#value: u8 } }\n", 2)?;
    if shapes[0] != shapes[1] {
        return Err("contract shape result changed with input order".into());
    }
    let shape_projection = shapes[0]
        .as_ref()
        .map_err(|error| format!("fixed valid shapes failed: {error}"))?;
    let valid_docs = contracts(b"#[doc = \" first \" ] #[r#doc = r#\"second\"#] #[boxology::contract] struct Named { #[doc = \"\"] value: u8 }\n#[doc = \"tuple\"] #[boxology::contract] struct Tuple(#[doc = \" tuple field \" ] u8);\n#[boxology::contract] struct Unit;\n#[doc = \"enum\"] #[boxology::contract(error)] enum Event { #[doc = \"unit variant\"] Unit, #[doc = \"tuple variant\"] Tuple(#[doc = \"tuple field\"] u8), #[doc = \"named variant\"] Named { #[doc = \"\"] value: u8 } }\n", 3)?;
    let invalid_docs = contracts(b"#[doc] #[boxology::contract] struct Invalid { #[doc = 7] field: u8 }\n#[boxology::contract] enum InvalidEvent { #[doc(private)] Bad { #[r#doc = concat!(\"private\")] field: u8 } }\n", 3)?;
    if valid_docs[0] != valid_docs[1] || invalid_docs[0] != invalid_docs[1] {
        return Err("contract documentation result changed with input order".into());
    }
    let docs = valid_docs[0]
        .as_ref()
        .map_err(|error| format!("fixed valid documentation failed: {error}"))?;
    let doc_diagnostics = invalid_docs[0]
        .as_ref()
        .expect_err("fixed invalid documentation must fail");
    let valid_members = contracts(
        b"#[boxology::contract]\nstruct First { r#type: u8, field: u16 }\n#[boxology::contract(error)]\nenum Event { r#match, Named { r#type: u8, field: u16 }, Tuple(u8), Unit }\n",
        2,
    )?;
    let invalid_members = contracts(
        b"#[boxology::contract]\nstruct PrivateOne { PrivateField: u8, PrivateField: u16 }\n#[boxology::contract(error)]\nenum PrivateEvent { PrivateVariant { PrivateNested: u8, PrivateNested: u16 }, PrivateVariant }\n",
        2,
    )?;
    if valid_members[0] != valid_members[1] || invalid_members[0] != invalid_members[1] {
        return Err("contract member result changed with input order".into());
    }
    let member_projection = valid_members[0]
        .as_ref()
        .map_err(|error| format!("fixed valid members failed: {error}"))?;
    let member_diagnostics = invalid_members[0]
        .as_ref()
        .expect_err("fixed invalid members must fail");
    let placement = |root: &[u8], child: &[u8]| -> Result<_, String> {
        let evaluate = |reversed| -> Result<_, String> {
            let mut files = vec![
                input("boxology.toml", request.inputs()[0].bytes()),
                input("placement/root.rs", root),
                input("placement/child.rs", child),
            ];
            if reversed {
                files.reverse();
            }
            let case =
                GenerationRequest::new(id(), "placement/root.rs".into(), files, vec![], vec![])
                    .map_err(|error| format!("fixed placement request failed: {error}"))?;
            let parsed = ParsedRustInputs::parse(&case)
                .map_err(|error| format!("fixed placement inputs failed: {error}"))?;
            let contracts = parsed.discover_contract_declarations();
            if contracts.as_ref().is_ok_and(Vec::is_empty) {
                return Ok(parsed.discover_capability_declarations().map(|items| {
                    items
                        .iter()
                        .map(|item| {
                            format!(
                                "{}|{:?}|{}|{:?}|{}",
                                item.method().sig.ident,
                                item.module_path(),
                                item.source().as_str(),
                                item.identifier_span(),
                                item.implementation().items.len()
                            )
                        })
                        .collect::<Vec<_>>()
                        .join("\n")
                }));
            }
            Ok(contracts.map(|items| {
                items
                    .iter()
                    .map(|item| item.lifted_name())
                    .collect::<Vec<_>>()
                    .join("\n")
            }))
        };
        let results = [evaluate(false)?, evaluate(true)?];
        if results[0] != results[1] {
            return Err("contract placement result changed with input order".into());
        }
        Ok(results.into_iter().next().unwrap())
    };
    let placement_projection = placement(
        b"mod child;\n#[boxology::contract] struct Root;\n",
        b"#[::boxology::contract(error)] enum Fault { A }\n",
    )?
    .map_err(|error| format!("fixed valid placement failed: {error}"))?;
    let placement_diagnostics = placement(
        b"mod child;\n#[boxology::contract(PrivateList)] fn PrivateRoot() {}\n",
        b"struct Hidden { #[::boxology::contract = \"PrivateValue\"] value: u8 }\n",
    )?
    .expect_err("fixed invalid placement must fail");
    let capability_projection = placement(
        b"mod child; struct Root; impl Root { #[boxology::capability] fn root() {} } mod inline { struct Inline; impl Inline { #[::r#boxology::r#capability] fn inline() {} } } fn outer() { mod local { struct Host; impl Host { #[boxology::capability] fn cap() {} } } } #[holder = { struct Phantom; impl Phantom { #[cfg(Private)] #[boxology::capability] fn hidden() {} } }] fn payload() {}\n",
        b"struct Child; impl Child { #[::boxology::capability] fn child() {} }\n",
    )?.map_err(|error| format!("fixed valid capability placement failed: {error}"))?;
    let expected_capabilities = "root|[]|placement/root.rs|Span { start: LineColumn { line: 1, column: 64 }, end: LineColumn { line: 1, column: 68 } }|1\nchild|[\"child\"]|placement/child.rs|Span { start: LineColumn { line: 1, column: 57 }, end: LineColumn { line: 1, column: 62 } }|1\ninline|[\"inline\"]|placement/root.rs|Span { start: LineColumn { line: 1, column: 151 }, end: LineColumn { line: 1, column: 157 } }|1\ncap|[\"local\"]|placement/root.rs|Span { start: LineColumn { line: 1, column: 244 }, end: LineColumn { line: 1, column: 247 } }|1";
    if capability_projection != expected_capabilities {
        return Err("fixed capability projection changed".into());
    }
    let capability_diagnostics = placement(
        b"mod child; #[boxology::capability] fn PrivatePath() {} #[boxology::capability(PrivateList)] trait PrivateTrait {}\n",
        b"struct Hidden { #[::boxology::capability = \"PrivateValue\"] value: u8 }\n",
    )?.expect_err("fixed invalid capability placement must fail");
    let capability_signatures = |reversed| -> Result<String, String> {
        let mut files = vec![
            input(
                "boxology.toml",
                b"schema = 1\nid = \"subject-box\"\nkind = \"box\"\n",
            ),
            input(
                "calls/root.rs",
                b"mod child; struct Root; impl Root { #[boxology::capability] pub async fn root(&self, request: PrivateRequest, context: PrivateContext) -> PrivateResponse { loop {} } }\n",
            ),
            input(
                "calls/child.rs",
                b"struct Child; impl Child { #[boxology::capability(PrivateMetadata)] async fn child(&self, request: [Private; 7], context: fn(Private)) -> impl PrivateOutput { loop {} } }\n",
            ),
        ];
        if reversed {
            files.reverse();
        }
        let case = GenerationRequest::new(id(), "calls/root.rs".into(), files, vec![], vec![])
            .map_err(|error| format!("fixed capability-signature request failed: {error}"))?;
        let parsed = ParsedRustInputs::parse(&case)
            .map_err(|error| format!("fixed capability-signature inputs failed: {error}"))?;
        let valid = parsed
            .validate_capability_call_shapes()
            .map_err(|error| format!("fixed valid capability signatures failed: {error}"))?
            .into_iter()
            .map(|item| {
                format!(
                    "{}|{:?}|{}|{:?}",
                    item.method().sig.ident,
                    item.module_path(),
                    item.source().as_str(),
                    item.identifier_span()
                )
            })
            .collect::<Vec<_>>()
            .join("\n");
        let mut invalid_files = vec![
            input(
                "boxology.toml",
                b"schema = 1\nid = \"subject-box\"\nkind = \"box\"\n",
            ),
            input(
                "calls/root.rs",
                b"mod child; struct Root; impl Root { #[boxology::capability] fn invalid_root(&mut self) {} }\n",
            ),
            input(
                "calls/child.rs",
                b"struct Child; impl Child { #[boxology::capability] async fn invalid_child(self: &Self, request: Private, context: Private) {} }\n",
            ),
        ];
        if reversed {
            invalid_files.reverse();
        }
        let invalid_case =
            GenerationRequest::new(id(), "calls/root.rs".into(), invalid_files, vec![], vec![])
                .map_err(|error| {
                    format!("fixed invalid capability-signature request failed: {error}")
                })?;
        let invalid_inputs = ParsedRustInputs::parse(&invalid_case).map_err(|error| {
            format!("fixed invalid capability-signature inputs failed: {error}")
        })?;
        let invalid = match invalid_inputs.validate_capability_call_shapes() {
            Ok(_) => return Err("fixed invalid call shapes unexpectedly passed".into()),
            Err(diagnostics) => diagnostics,
        };
        Ok(format!("success\n{valid}\ninvalid\n{invalid}\n"))
    };
    let capability_signatures_forward = capability_signatures(false)?;
    if capability_signatures_forward != capability_signatures(true)? {
        return Err("capability signature result changed with input order".into());
    }
    let capability_metadata = |reversed| -> Result<String, String> {
        let mut files = vec![
            input("boxology.toml", request.inputs()[0].bytes()),
            input("metadata/root.rs", b"mod child; struct Root; impl Root { #[boxology::capability] async fn BadName(&self, a: A, b: B) -> R { loop {} } #[boxology::capability(name = \"Bad-Override\", exposure = \"internal\", idempotency = \"inherent\",)] async fn raw(&self, a: A, b: B) -> R { loop {} } }"),
            input("metadata/child.rs", b"struct Child; impl Child { #[boxology::capability(name = \"greet\", exposure = \"external\")] async fn hello(&self, a: A, b: B) -> R { loop {} } }"),
        ];
        if reversed {
            files.reverse();
        }
        let case = GenerationRequest::new(id(), "metadata/root.rs".into(), files, vec![], vec![])
            .map_err(|error| format!("fixed capability-metadata request failed: {error}"))?;
        let parsed = ParsedRustInputs::parse(&case)
            .map_err(|error| format!("fixed capability-metadata inputs failed: {error}"))?;
        let projection = parsed
            .validate_capability_marker_metadata()
            .map_err(|error| format!("fixed capability metadata failed: {error}"))?
            .iter()
            .map(|item| {
                format!(
                    "{}|{:?}|{:?}|{:?}",
                    item.method().sig.ident,
                    item.marker_metadata().name_override(),
                    item.marker_metadata().max_exposure(),
                    item.marker_metadata().idempotency()
                )
            })
            .collect::<Vec<_>>()
            .join("\n");
        let invalid = GenerationRequest::new(id(), "invalid.rs".into(), vec![input("boxology.toml", request.inputs()[0].bytes()), input("invalid.rs", b"struct H; impl H { #[boxology::capability(DO_NOT_LEAK = \"private\")] async fn a(&self, x: A, y: B) -> R { loop {} } #[boxology::capability(idempotency = \"keyed\")] async fn b(&self, x: A, y: B) -> R { loop {} } }")], vec![], vec![])
            .map_err(|error| format!("fixed invalid metadata request failed: {error}"))?;
        let diagnostics = ParsedRustInputs::parse(&invalid)
            .unwrap()
            .validate_capability_marker_metadata()
            .err()
            .ok_or("fixed invalid metadata must fail")?;
        let rendered = format!("{diagnostics}\n{diagnostics:?}");
        if rendered.contains("DO_NOT_LEAK")
            || rendered.contains("private")
            || rendered.contains("keyed")
        {
            return Err("capability metadata diagnostic leaked payload".into());
        }
        Ok(format!("success\n{projection}\ninvalid\n{diagnostics}\n"))
    };
    let capability_metadata_forward = capability_metadata(false)?;
    if capability_metadata_forward != capability_metadata(true)? {
        return Err("capability metadata result changed with input order".into());
    }
    let capability_identities = |reversed| -> Result<String, String> {
        let make = |root: &[u8], child: &[u8]| -> Result<GenerationRequest, String> {
            let mut files = vec![
                input(
                    "boxology.toml",
                    b"schema = 1\nid = \"hello\"\nkind = \"box\"\n",
                ),
                input("identity/root.rs", root),
                input("identity/child.rs", child),
            ];
            if reversed {
                files.reverse();
            }
            GenerationRequest::new(
                BoxId::new("hello").unwrap(),
                "identity/root.rs".into(),
                files,
                vec![],
                vec![],
            )
            .map_err(|error| format!("fixed capability-identity request failed: {error}"))
        };
        let valid = make(
            b"mod child; struct H; impl H { #[boxology::capability] async fn default_name(&self, a: A, b: B) -> R { loop {} } #[boxology::capability(name = \"rescued\")] async fn BadName(&self, a: A, b: B) -> R { loop {} } #[boxology::capability] async fn r#type(&self, a: A, b: B) -> R { loop {} } }",
            b"struct C; impl C { #[boxology::capability(name = \"greet\", exposure = \"external\")] async fn hello(&self, a: A, b: B) -> R { loop {} } }",
        )?;
        let projection = ParsedRustInputs::parse(&valid)
            .map_err(|error| format!("fixed capability-identity inputs failed: {error}"))?
            .validate_capability_identities()
            .map_err(|error| format!("fixed capability identities failed: {error}"))?
            .iter()
            .map(|item| format!("{}|{:?}", item.id(), item.marker_metadata().name_override()))
            .collect::<Vec<_>>()
            .join("\n");
        let invalid = make(
            b"mod child; struct H; impl H { #[boxology::capability(name = \"DO_NOT_LEAK_\\u{e9}\")] async fn bad(&self, a: A, b: B) -> R { loop {} } }",
            b"",
        )?;
        let invalid_diagnostics = ParsedRustInputs::parse(&invalid)
            .unwrap()
            .validate_capability_identities()
            .err()
            .ok_or("fixed invalid capability identity must fail")?;
        let collision = make(
            b"mod child; struct H; impl H { #[boxology::capability] async fn do_not_leak_collision(&self, a: A, b: B) -> R { loop {} } }",
            b"struct C; impl C { #[boxology::capability(name = \"do_not_leak_collision\")] async fn other(&self, a: A, b: B) -> R { loop {} } }",
        )?;
        let collision_diagnostics = ParsedRustInputs::parse(&collision)
            .unwrap()
            .validate_capability_identities()
            .err()
            .ok_or("fixed capability collision must fail")?;
        let output = format!(
            "success\n{projection}\ninvalid-name\n{invalid_diagnostics}\ncollision\n{collision_diagnostics}\n"
        );
        if output.contains("DO_NOT_LEAK") || output.contains("do_not_leak_collision") {
            return Err("capability identity diagnostic leaked payload".into());
        }
        Ok(output)
    };
    let capability_identities_forward = capability_identities(false)?;
    if capability_identities_forward != capability_identities(true)? {
        return Err("capability identity result changed with input order".into());
    }
    let invalid_manifest_request = GenerationRequest::new(
        id(),
        "source/custom-entry.rs".into(),
        vec![
            (
                "boxology.toml".into(),
                b"schema = 1\nid = \"subject-box\"\nkind = \"composition\"\n".to_vec(),
            ),
            ("source/custom-entry.rs".into(), vec![]),
        ],
        vec![],
        vec![],
    )
    .map_err(|error| format!("fixed invalid-manifest request failed: {error}"))?;
    let manifest_diagnostics =
        Manifest::parse(&invalid_manifest_request).expect_err("fixed invalid manifest must fail");
    let invalid_rust_request = GenerationRequest::new(
        id(),
        "a.rs".into(),
        vec![
            ("boxology.toml".into(), b"manifest\n".to_vec()),
            ("b.rs".into(), "fn café() { @ }\n".as_bytes().to_vec()),
            ("a.rs".into(), b"fn good() {}\nfn bad() { @ }\n".to_vec()),
        ],
        vec![],
        vec![],
    )
    .map_err(|error| format!("fixed invalid-Rust request failed: {error}"))?;
    let rust_diagnostics = match ParsedRustInputs::parse(&invalid_rust_request) {
        Ok(_) => return Err("fixed invalid Rust inputs unexpectedly parsed".into()),
        Err(diagnostics) => diagnostics,
    };
    let invalid_module_request = GenerationRequest::new(
        id(),
        "modules/root.rs".into(),
        vec![
            (
                "boxology.toml".into(),
                b"schema = 1\nid = \"subject-box\"\nkind = \"box\"\n".to_vec(),
            ),
            (
                "modules/root.rs".into(),
                b"#[path = \"private.rs\"] mod redirected;\nmod missing;\nmod duplicate;\n"
                    .to_vec(),
            ),
            ("modules/duplicate.rs".into(), vec![]),
            ("modules/duplicate/mod.rs".into(), vec![]),
        ],
        vec![],
        vec![],
    )
    .map_err(|error| format!("fixed invalid-topology request failed: {error}"))?;
    let invalid_modules = ParsedRustInputs::parse(&invalid_module_request)
        .map_err(|error| format!("fixed invalid-topology Rust inputs failed: {error}"))?;
    let module_diagnostics = match invalid_modules.resolve_reachable_inputs() {
        Ok(_) => return Err("fixed invalid module topology unexpectedly resolved".into()),
        Err(diagnostics) => diagnostics,
    };
    let declaration_request = GenerationRequest::new(
        id(),
        "d/r.rs".into(),
        vec![
            input(
                "boxology.toml",
                b"schema = 1\nid = \"subject-box\"\nkind = \"box\"\n",
            ),
            input("d/r.rs", b"#[cfg(private)]\nmod exported;\n"),
            input("d/exported.rs", b"#[boxology::contract]\nstruct Export;\n"),
            input("d/dead.rs", b"#[boxology::capability]\nfn hidden() {}\n"),
        ],
        vec![],
        vec![],
    )
    .map_err(|error| format!("fixed declaration-error request failed: {error}"))?;
    let declaration_inputs = ParsedRustInputs::parse(&declaration_request)
        .map_err(|error| format!("fixed declaration-error inputs failed: {error}"))?;
    let declaration_diagnostics = match declaration_inputs.resolve_reachable_inputs() {
        Ok(_) => return Err("fixed declaration errors unexpectedly resolved".into()),
        Err(diagnostics) => diagnostics,
    };
    let diagnostics = GenerationRequest::new(
        id(),
        "root.rs".into(),
        vec![("root.rs".into(), vec![]), ("/absolute.rs".into(), vec![])],
        vec![],
        vec![],
    )
    .expect_err("fixed invalid request must fail");

    let marker_root = out
        .canonicalize()
        .map_err(|error| format!("canonicalize cold output: {error}"))?
        .join("cold-markers");
    let body_marker = marker_root.join("implementation-body");
    let initializer_marker = marker_root.join("static-initializer");
    let build_marker = marker_root.join("build-rs");
    let proc_macro_marker = marker_root.join("proc-macro");
    let marker_paths = [
        &body_marker,
        &initializer_marker,
        &build_marker,
        &proc_macro_marker,
    ];
    fs::create_dir_all(&marker_root)
        .map_err(|error| format!("create cold marker directory: {error}"))?;
    for marker in marker_paths {
        if marker.exists() {
            return Err(format!(
                "fixed cold marker was present before generation: {}",
                marker.display()
            ));
        }
    }
    let cold_hostile_source = format!(
        r#"boxology::contract! {{
    #[error] pub enum GreetError {{ EmptyName }}
    #[capability(exposure=external)] pub async fn greet(name:String)->Result<String,GreetError>;
}}

pub struct HelloService;
static BOXOLOGY_INITIALIZER: &str = include_str!({initializer_marker});
impl HelloService {{
    #[sentinel_proc_macro::attribute]
    async fn greet(&self, name: String) -> Result<String, GreetError> {{
        let _ = std::fs::write({body_marker}, b"BOXOLOGY_BODY_SENTINEL");
        panic!("BOXOLOGY_BODY_SENTINEL");
    }}
}}
"#,
        initializer_marker = rust_string_literal(&initializer_marker),
        body_marker = rust_string_literal(&body_marker),
    );
    let cold_request = GenerationRequest::new(
        BoxId::new("hello").expect("fixed id is valid"),
        "src/lib.rs".into(),
        vec![
            input("boxology.toml", b"schema = 1\nid = \"hello\"\nkind = \"box\"\n"),
            input("src/lib.rs", cold_hostile_source.as_bytes()),
            input(
                "Cargo.toml",
                b"[package]\nname=\"hostile\"\nversion=\"0.0.0\"\nbuild=\"build.rs\"\n",
            ),
            input(
                "build.rs",
                format!(
                    "fn main() {{ let _ = std::fs::write({build_marker}, b\"BOXOLOGY_BUILD_SENTINEL\"); panic!(\"BOXOLOGY_BUILD_SENTINEL\"); compile_error!(\"BOXOLOGY_BUILD_SENTINEL\"); }}",
                    build_marker = rust_string_literal(&build_marker),
                )
                .as_bytes(),
            ),
            input(
                "proc-macro.rs",
                format!(
                    "extern crate proc_macro; #[proc_macro::proc_macro] pub fn hostile(_: proc_macro::TokenStream) -> proc_macro::TokenStream {{ let _ = std::fs::write({proc_macro_marker}, b\"BOXOLOGY_PROC_MACRO_SENTINEL\"); panic!(\"BOXOLOGY_PROC_MACRO_SENTINEL\"); compile_error!(\"BOXOLOGY_PROC_MACRO_SENTINEL\"); }}",
                    proc_macro_marker = rust_string_literal(&proc_macro_marker),
                )
                .as_bytes(),
            ),
        ],
        vec![],
        OUTPUTS.iter().map(|path| (*path).into()).collect(),
    )
    .map_err(|error| format!("fixed cold request failed: {error}"))?;
    let cold_contract = ParsedRustInputs::parse(&cold_request)
        .and_then(|parsed| parsed.controlled_contract())
        .map_err(|error| format!("fixed cold contract failed: {error}"))?;
    fs::create_dir_all(out.join("cold-model"))
        .map_err(|error| format!("create cold-model: {error}"))?;
    fs::write(
        out.join("cold-model/semantic.bin"),
        cold_contract.canonical_semantic_bytes(),
    )
    .map_err(|error| format!("write cold semantic model: {error}"))?;
    fs::write(
        out.join("cold-model/digest.bin"),
        cold_contract.semantic_digest(),
    )
    .map_err(|error| format!("write cold semantic digest: {error}"))?;
    let cold_output =
        generate(cold_request).map_err(|error| format!("fixed cold generation failed: {error}"))?;
    let hostile_sentinels = [
        "BOXOLOGY_BODY_SENTINEL",
        "BOXOLOGY_INITIALIZER_SENTINEL",
        "BOXOLOGY_BUILD_SENTINEL",
        "BOXOLOGY_PROC_MACRO_SENTINEL",
    ];
    for marker in marker_paths {
        if marker.exists() {
            return Err(format!(
                "fixed cold generation executed a hostile marker: {}",
                marker.display()
            ));
        }
    }
    fs::remove_dir(&marker_root)
        .map_err(|error| format!("remove cold marker directory: {error}"))?;
    let marker_texts = marker_paths
        .into_iter()
        .flat_map(|marker| {
            [
                marker.to_string_lossy().into_owned(),
                rust_string_literal(marker),
            ]
        })
        .collect::<Vec<_>>();
    if cold_output.files().iter().any(|file| {
        let bytes = String::from_utf8_lossy(file.bytes());
        hostile_sentinels
            .iter()
            .any(|sentinel| bytes.contains(sentinel))
            || marker_texts.iter().any(|marker| bytes.contains(marker))
    }) {
        return Err("fixed cold generation leaked a hostile sentinel or marker path".into());
    }
    for file in cold_output.files() {
        let destination = out.join("cold-output").join(file.path());
        fs::create_dir_all(destination.parent().expect("generated file has parent"))
            .map_err(|error| format!("create cold output parent: {error}"))?;
        fs::write(&destination, file.bytes())
            .map_err(|error| format!("write {}: {error}", destination.display()))?;
    }
    let payload_subject = |reversed| -> Result<(Vec<u8>, Vec<u8>, String), String> {
        let mut inputs = vec![
            input("boxology.toml", b"schema = 1\nid = \"subject-box\"\nkind = \"box\"\n"),
            input("payload/src/lib.rs", b"boxology::contract! { #[error] pub enum Fault { Code(u32), Detail { message: String } } #[capability(exposure=external)] pub async fn greet(name:String)->Result<String,Fault>; }"),
            input("unrelated.rs", b"fn unrelated() {}\n"),
        ];
        if reversed {
            inputs.reverse();
        }
        let request =
            GenerationRequest::new(id(), "payload/src/lib.rs".into(), inputs, vec![], vec![])
                .map_err(|error| format!("payload subject request failed: {error}"))?;
        let contract = ParsedRustInputs::parse(&request)
            .and_then(|parsed| parsed.controlled_contract())
            .map_err(|error| format!("payload subject parse failed: {error}"))?;
        let diagnostics = contract
            .require_v0_emittable()
            .expect_err("payload subject must remain fail-closed");
        Ok((
            contract.canonical_semantic_bytes().to_vec(),
            contract.semantic_digest().to_vec(),
            diagnostics.to_string(),
        ))
    };
    let payload_forward = payload_subject(false)?;
    if payload_forward != payload_subject(true)? {
        return Err("payload subject changed with unrelated input order".into());
    }
    if payload_forward.2
        != "BXG0048 payload/src/lib.rs:1:11-1:19 offending=\"named-field error variants are not yet emittable\" rule=\"named-field payloads require contract-emitter support\" source=\"specs/s2-contract-generator.md D3\""
    {
        return Err("payload subject diagnostic changed".into());
    }
    fs::create_dir_all(out.join("cold-payload"))
        .map_err(|error| format!("create cold-payload: {error}"))?;
    fs::write(out.join("cold-payload/semantic.bin"), &payload_forward.0)
        .map_err(|error| format!("write cold payload semantic bytes: {error}"))?;
    fs::write(out.join("cold-payload/digest.bin"), &payload_forward.1)
        .map_err(|error| format!("write cold payload digest: {error}"))?;
    fs::write(
        out.join("cold-payload/fail-closed.txt"),
        format!("{}\n", payload_forward.2),
    )
    .map_err(|error| format!("write cold payload diagnostic: {error}"))?;
    fs::write(
        out.join("cold-purity.txt"),
        "inputs=implementation-body,static-initializer,build-script,proc-macro\noutput=exact-four-generated-files-without-hostile-sentinels\nexecution=generator-observed-no-body-build-or-proc-macro-effects\nmarker-absence=subject-asserted\n",
    )
    .map_err(|error| format!("write cold-purity.txt: {error}"))?;
    run_fixture_suite(out)?;

    let summary = format!(
        "box_id={}\ncrate_root={}\ninputs={}\nimports={}\noutputs={}\n",
        request.box_id(),
        request.crate_root().as_str(),
        request.inputs().len(),
        request.imports().len(),
        request.outputs().len()
    );
    fs::write(out.join("request.txt"), summary)
        .map_err(|error| format!("write request.txt: {error}"))?;
    fs::write(out.join("diagnostics.txt"), format!("{diagnostics}\n"))
        .map_err(|error| format!("write diagnostics.txt: {error}"))?;
    fs::write(
        out.join("manifest.txt"),
        format!("manifest_id={}\n", manifest.id()),
    )
    .map_err(|error| format!("write manifest.txt: {error}"))?;
    fs::write(
        out.join("manifest-diagnostics.txt"),
        format!("{manifest_diagnostics}\n"),
    )
    .map_err(|error| format!("write manifest-diagnostics.txt: {error}"))?;
    let rust_summary = rust_inputs
        .as_slice()
        .iter()
        .map(|input| {
            format!(
                "{} items={}",
                input.path().as_str(),
                input.syntax().items.len()
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    fs::write(out.join("rust-inputs.txt"), format!("{rust_summary}\n"))
        .map_err(|error| format!("write rust-inputs.txt: {error}"))?;
    fs::write(out.join("rust-modules.txt"), format!("{rust_modules}\n"))
        .map_err(|error| format!("write rust-modules.txt: {error}"))?;
    fs::write(
        out.join("module-diagnostics.txt"),
        format!("{module_diagnostics}\n"),
    )
    .map_err(|error| format!("write module-diagnostics.txt: {error}"))?;
    fs::write(
        out.join("declaration-diagnostics.txt"),
        format!("{declaration_diagnostics}\n"),
    )
    .map_err(|error| format!("write declaration-diagnostics.txt: {error}"))?;
    fs::write(
        out.join("contract-declarations.txt"),
        format!("success\n{declaration_projection}\ncollision\n{collision_diagnostics}\n"),
    )
    .map_err(|error| format!("write contract-declarations.txt: {error}"))?;
    fs::write(
        out.join("contract-attributes.txt"),
        format!(
            "success count={}\n{attribute_projection}\ninvalid\n{attribute_diagnostics}\n",
            attribute_projection.lines().count()
        ),
    )
    .map_err(|error| format!("write contract-attributes.txt: {error}"))?;
    fs::write(
        out.join("contract-roles.txt"),
        format!("success\n{role_projection}\ninvalid\n{role_diagnostics}\n"),
    )
    .map_err(|error| format!("write contract-roles.txt: {error}"))?;
    fs::write(
        out.join("contract-deprecations.txt"),
        format!("success\n{deprecation_projection}\ninvalid\n{deprecation_diagnostics}\n"),
    )
    .map_err(|error| format!("write contract-deprecations.txt: {error}"))?;
    fs::write(
        out.join("contract-shapes.txt"),
        format!("success\n{shape_projection}\n"),
    )
    .map_err(|error| format!("write contract-shapes.txt: {error}"))?;
    fs::write(
        out.join("contract-docs.txt"),
        format!("success\n{docs}\ninvalid\n{doc_diagnostics}\n"),
    )
    .map_err(|error| format!("write contract-docs.txt: {error}"))?;
    fs::write(
        out.join("contract-members.txt"),
        format!("success\n{member_projection}\ninvalid\n{member_diagnostics}\n"),
    )
    .map_err(|error| format!("write contract-members.txt: {error}"))?;
    fs::write(
        out.join("contract-placement.txt"),
        format!("success\n{placement_projection}\ninvalid\n{placement_diagnostics}\n"),
    )
    .map_err(|error| format!("write contract-placement.txt: {error}"))?;
    fs::write(
        out.join("capability-placement.txt"),
        format!("success\n{capability_projection}\ninvalid\n{capability_diagnostics}\n",),
    )
    .map_err(|error| format!("write capability-placement.txt: {error}"))?;
    fs::write(
        out.join("capability-signatures.txt"),
        capability_signatures_forward,
    )
    .map_err(|error| format!("write capability-signatures.txt: {error}"))?;
    fs::write(
        out.join("capability-metadata.txt"),
        capability_metadata_forward,
    )
    .map_err(|error| format!("write capability-metadata.txt: {error}"))?;
    fs::write(
        out.join("capability-identities.txt"),
        capability_identities_forward,
    )
    .map_err(|error| format!("write capability-identities.txt: {error}"))?;
    fs::write(
        out.join("rust-diagnostics.txt"),
        format!("{rust_diagnostics}\n"),
    )
    .map_err(|error| format!("write rust-diagnostics.txt: {error}"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io;
    use std::path::PathBuf;
    use std::sync::atomic::{AtomicU64, Ordering};

    static NEXT_SUBJECT: AtomicU64 = AtomicU64::new(0);

    struct SubjectTemp(PathBuf);
    impl Drop for SubjectTemp {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.0);
        }
    }

    fn subject_root(name: &str) -> SubjectTemp {
        let parent = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../target/xtask-subject-tests");
        fs::create_dir_all(&parent).unwrap();
        let path = loop {
            let candidate = parent.join(format!(
                "{name}-{}-{}",
                std::process::id(),
                NEXT_SUBJECT.fetch_add(1, Ordering::Relaxed)
            ));
            match fs::create_dir(&candidate) {
                Ok(()) => break candidate,
                Err(error) if error.kind() == io::ErrorKind::AlreadyExists => continue,
                Err(error) => panic!("create subject root: {error}"),
            }
        };
        SubjectTemp(path)
    }

    fn fixture_scratch(name: &str) -> SubjectTemp {
        let path = loop {
            let candidate = std::env::temp_dir().join(format!(
                "boxology-fixture-{name}-{}-{}",
                std::process::id(),
                NEXT_SUBJECT.fetch_add(1, Ordering::Relaxed)
            ));
            match fs::create_dir(&candidate) {
                Ok(()) => break candidate,
                Err(error) if error.kind() == io::ErrorKind::AlreadyExists => continue,
                Err(error) => panic!("create fixture scratch: {error}"),
            }
        };
        SubjectTemp(path)
    }

    #[test]
    fn subject_root_skips_same_pid_residue() {
        crate::scratch_test::assert_skips_same_pid_residue(
            &Path::new(env!("CARGO_MANIFEST_DIR")).join("../../target/xtask-subject-tests"),
            "residue",
            &NEXT_SUBJECT,
            || subject_root("residue"),
            |t| &t.0,
        );
    }

    #[test]
    fn fixture_scratch_skips_same_pid_residue() {
        crate::scratch_test::assert_skips_same_pid_residue(
            &std::env::temp_dir(),
            "boxology-fixture-residue",
            &NEXT_SUBJECT,
            || fixture_scratch("residue"),
            |t| &t.0,
        );
    }

    #[test]
    fn fixture_owner_mutants_are_rejected() {
        let valid = ["greeter", "hello", "ping"];
        assert!(validate_fixture_owners(&valid, &valid).is_ok());
        assert!(validate_fixture_owners(&valid, &["greeter", "hello", "other"]).is_err());
        assert!(validate_fixture_owners(&["greeter", "hello", "hello"], &valid).is_err());
        assert!(validate_fixture_owners(&valid, &["greeter", "hello"]).is_err());
    }

    #[cfg(unix)]
    #[test]
    fn fixture_owner_symlink_is_rejected() {
        use std::os::unix::fs::symlink;
        let root = fixture_scratch("symlink");
        fs::create_dir(root.0.join("target")).unwrap();
        symlink(root.0.join("target"), root.0.join("owner")).unwrap();
        assert!(discover_fixture_schema_owners_at(&root.0).is_err());
    }

    #[test]
    fn rust_header_mutants_are_rejected() {
        let valid = b"// Generated by boxology-generator 0.0.0\nconst MARKER: &str = \"// Generated by boxology-generator body\";\n";
        assert!(normalize_rust(valid).is_ok());
        for mutant in [
            b"// Generated by boxology-generator 0.0.0\n// Generated by boxology-generator 0.0.0\nfn generated() {}\n".as_slice(),
            b"fn generated() {}\n// Generated by boxology-generator 0.0.0\n".as_slice(),
            b"fn generated() {}\n".as_slice(),
        ] {
            assert!(normalize_rust(mutant).is_err());
        }
    }

    #[test]
    fn schema_provenance_mutants_are_rejected_before_normalization() {
        let live = br#"{"revision":"r","provenance":{"generator":"g"},"nested":{"b":1,"a":2}}"#;
        let golden = br#"{"nested":{"a":2,"b":1},"provenance":"@PROVENANCE@","revision":"r"}"#;
        assert_eq!(
            normalize_schema(live, SchemaBytes::Live).unwrap(),
            normalize_schema(golden, SchemaBytes::Golden).unwrap()
        );
        for mutant in [
            br#"{"provenance":{},"provenance":{},"revision":"r"}"#.as_slice(),
            br#"{"provenance":"@PROVENANCE@","revision":"r"}"#,
            br#"{"revision":"r","revision":"r","provenance":{}}"#,
            br#"{"revision":"r","provenance":{},"nested":{"a":1,"a":1}}"#,
        ] {
            assert!(normalize_schema(mutant, SchemaBytes::Live).is_err());
        }
        let wrong = br#"{"provenance":"wrong","revision":"r"}"#;
        assert!(normalize_schema(wrong, SchemaBytes::Golden).is_err());
    }

    #[test]
    fn schema_revision_and_non_provenance_mutants_are_not_hidden() {
        let golden = br#"{"provenance":"@PROVENANCE@","revision":"r","nested":{"a":2,"b":1}}"#;
        let revision =
            br#"{"revision":"changed","provenance":{"generator":"g"},"nested":{"b":1,"a":2}}"#;
        let non_provenance =
            br#"{"revision":"r","provenance":{"generator":"g"},"nested":{"b":3,"a":2}}"#;
        let expected = normalize_schema(golden, SchemaBytes::Golden).unwrap();
        assert_ne!(
            normalize_schema(revision, SchemaBytes::Live).unwrap(),
            expected
        );
        assert_ne!(
            normalize_schema(non_provenance, SchemaBytes::Live).unwrap(),
            expected
        );
        for (actual, expected, equal) in [
            (b"[package]\n".as_slice(), b"[package]\n".as_slice(), true),
            (b"[package]\n".as_slice(), b"[package] \n".as_slice(), false),
        ] {
            assert_eq!(
                compare_fixture_output(
                    &FIXTURES[1],
                    "generated/contract/Cargo.toml",
                    actual,
                    expected
                )
                .is_ok(),
                equal
            );
        }
    }

    #[test]
    fn subject_call_publishes_raw_fixture_goldens() {
        let root = subject_root("goldens");
        run(&root.0).unwrap();
        for fixture in &FIXTURES {
            let generated = generate(fixture_request(fixture).unwrap()).unwrap();
            for file in generated.files() {
                let path = root
                    .0
                    .join("fixture-goldens")
                    .join(fixture.name)
                    .join(file.path());
                assert_eq!(fs::read(path).unwrap(), file.bytes());
            }
        }
    }
}
