[package]
name = "check-implementation"
version = "0.0.0"
edition.workspace = true
publish = false

[dependencies]
boxology = { version = "=0.0.0", path = "../../boxology" }
boxology-cli-core = { version = "=0.0.0", path = "../../boxology-cli-core" }
boxology-contract = { version = "=0.0.0", path = "../../boxology-contract" }
boxology-manifest = { version = "=0.0.0", path = "../../boxology-manifest" }
boxology-runtime = { version = "=0.0.0", path = "../../boxology-runtime" }
boxology-workspace = { version = "=0.0.0", path = "../../boxology-workspace" }
boxology_generated_contract = { package = "check-contract", version = "=0.0.0", path = "../generated/contract" }
boxology_import_classifier = { package = "classifier-contract", version = "=0.0.0", path = "../../boxology-classifier/generated/contract" }
serde_json = { version = "=1.0.150", default-features = false, features = ["std"] }
