[package]
name = "boxology-manifest"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
description = "Strict manifest parser and model"
publish = false

[dependencies]
boxology-contract = { version = "=0.0.0", path = "../boxology-contract" }
toml_edit = "=0.25.13+spec-1.1.0"
