//! Pure generation of deterministic Boxology artifacts from validated logical inputs.
#![deny(missing_docs)]
#![forbid(unsafe_code)]

use boxology_generator_model::{Diagnostics, GenerationRequest, ParsedRustInputs};

const OUTPUTS: [&str; 2] = [
    "generated/contract/Cargo.toml",
    "generated/contract/src/lib.rs",
];

/// One generated logical file.
#[derive(Debug, Eq, PartialEq)]
pub struct GeneratedFile {
    path: String,
    bytes: Vec<u8>,
}

impl GeneratedFile {
    /// Returns the generated file's logical path.
    pub fn path(&self) -> &str {
        &self.path
    }

    /// Returns the generated file's exact bytes.
    pub fn bytes(&self) -> &[u8] {
        &self.bytes
    }
}

/// A generated tree sorted by logical-path bytes.
#[derive(Debug, Eq, PartialEq)]
pub struct GeneratedTree(Vec<GeneratedFile>);

impl GeneratedTree {
    /// Returns all generated files in canonical logical-path order.
    pub fn files(&self) -> &[GeneratedFile] {
        &self.0
    }
}

/// Generates the current controlled contract-package scaffold without external I/O.
///
/// # Errors
/// Returns sorted model diagnostics when the request, source topology, controlled contract, or
/// complete output declaration is invalid.
pub fn generate(request: &GenerationRequest) -> Result<GeneratedTree, Diagnostics> {
    request.require_exact_outputs(&OUTPUTS)?;
    let parsed = ParsedRustInputs::parse(request)?;
    let contract = parsed.controlled_contract()?;
    let manifest = format!(
        "[package]\nname = \"{}-contract\"\nversion = \"0.0.0\"\nedition = \"2024\"\npublish = false\n",
        request.box_id().as_str()
    );
    let digest = contract
        .semantic_digest()
        .iter()
        .map(u8::to_string)
        .collect::<Vec<_>>()
        .join(", ");
    let syntax = syn::parse_file(&format!(
        "#[doc(hidden)] pub const __BOXOLOGY_SEMANTIC_DIGEST: [u8; 32] = [{digest}];"
    ))
    .expect("fixed generator template must parse");
    let rust = format!(
        "// Generated by boxology-generator {}\n{}",
        env!("CARGO_PKG_VERSION"),
        prettyplease::unparse(&syntax)
    );
    let mut files = OUTPUTS
        .iter()
        .zip([manifest.into_bytes(), rust.into_bytes()])
        .map(|(path, bytes)| GeneratedFile {
            path: (*path).to_owned(),
            bytes,
        })
        .collect::<Vec<_>>();
    files.sort_by(|left, right| left.path.as_bytes().cmp(right.path.as_bytes()));
    Ok(GeneratedTree(files))
}

#[cfg(test)]
mod tests {
    use super::*;
    use boxology_contract::BoxId;

    const MANIFEST: &[u8] = b"schema = 1\nid = \"hello\"\nkind = \"box\"\n";
    const CONTRACT: &str = "boxology::contract! { #[error] pub enum GreetError { EmptyName } #[capability(exposure=external)] pub async fn greet(name:String)->Result<String,GreetError>; }";
    const CARGO: &[u8] = b"[package]\nname = \"hello-contract\"\nversion = \"0.0.0\"\nedition = \"2024\"\npublish = false\n";
    const RUST: &[u8] = b"// Generated by boxology-generator 0.0.0\n#[doc(hidden)]\npub const __BOXOLOGY_SEMANTIC_DIGEST: [u8; 32] = [\n    84, 95, 20, 43, 12, 237, 118, 112, 227, 249, 239, 199, 188, 170, 243, 183, 162, 160,\n    178, 183, 144, 229, 180, 138, 202, 168, 94, 73, 1, 200, 155, 24,\n];\n";

    fn request(source: &str, reverse: bool, outputs: Vec<&str>) -> GenerationRequest {
        let mut inputs = vec![
            ("boxology.toml".into(), MANIFEST.to_vec()),
            ("src/lib.rs".into(), source.as_bytes().to_vec()),
        ];
        if reverse {
            inputs.reverse();
        }
        GenerationRequest::new(
            BoxId::new("hello").unwrap(),
            "src/lib.rs".into(),
            inputs,
            vec![],
            outputs.into_iter().map(str::to_owned).collect(),
        )
        .unwrap()
    }

    fn tree(source: &str, reverse: bool) -> GeneratedTree {
        generate(&request(source, reverse, OUTPUTS.to_vec())).unwrap()
    }

    fn marker_parts(bytes: &[u8]) -> (&str, &str, &str) {
        let text = std::str::from_utf8(bytes).unwrap();
        let start = text.find("= [").unwrap() + 3;
        let end = text.find("];\n").unwrap();
        (&text[..start], &text[start..end], &text[end..])
    }

    #[test]
    fn cold_hello_bytes_are_exact_and_parseable() {
        let tree = tree(CONTRACT, false);
        assert_eq!(
            tree.files()
                .iter()
                .map(GeneratedFile::path)
                .collect::<Vec<_>>(),
            OUTPUTS
        );
        assert_eq!(tree.files()[0].bytes(), CARGO);
        assert_eq!(tree.files()[1].bytes(), RUST);
        let rust = std::str::from_utf8(tree.files()[1].bytes()).unwrap();
        assert!(rust.starts_with("// Generated by boxology-generator 0.0.0\n"));
        syn::parse_file(rust).unwrap();
    }

    #[test]
    fn spelling_and_order_do_not_change_artifacts() {
        let decorated = "// ignored\nboxology::contract! { #[error] pub enum GreetError { EmptyName } /* ignored */ #[capability(exposure = external)] pub async fn greet(name: String) -> Result<String, GreetError>; }";
        assert_eq!(tree(CONTRACT, false), tree(decorated, true));
        assert_eq!(
            generate(&request(
                CONTRACT,
                true,
                OUTPUTS.iter().rev().copied().collect()
            ))
            .unwrap(),
            tree(CONTRACT, false)
        );
    }

    #[test]
    fn semantic_change_only_changes_digest_marker() {
        let changed = CONTRACT.replace("EmptyName", "MissingName");
        let before = tree(CONTRACT, false);
        let after = tree(&changed, false);
        assert_eq!(before.files()[0], after.files()[0]);
        let before = marker_parts(before.files()[1].bytes());
        let after = marker_parts(after.files()[1].bytes());
        assert_eq!((before.0, before.2), (after.0, after.2));
        assert_ne!(before.1, after.1);
    }

    #[test]
    fn output_set_fails_closed_with_one_stable_code() {
        let cases = [
            (
                vec![OUTPUTS[0]],
                r#"BXG0039 <request>:1:1-1:1 offending="declared outputs [\"generated/contract/Cargo.toml\"]" rule="declared outputs must equal the generator's complete output set without duplicates" source="specs/s2-contract-generator.md D1""#,
            ),
            (
                vec![OUTPUTS[0], OUTPUTS[1], "generated/extra"],
                r#"BXG0039 <request>:1:1-1:1 offending="declared outputs [\"generated/contract/Cargo.toml\", \"generated/contract/src/lib.rs\", \"generated/extra\"]" rule="declared outputs must equal the generator's complete output set without duplicates" source="specs/s2-contract-generator.md D1""#,
            ),
            (
                vec![OUTPUTS[0], OUTPUTS[1], OUTPUTS[1]],
                r#"BXG0039 <request>:1:1-1:1 offending="declared outputs [\"generated/contract/Cargo.toml\", \"generated/contract/src/lib.rs\", \"generated/contract/src/lib.rs\"]" rule="declared outputs must equal the generator's complete output set without duplicates" source="specs/s2-contract-generator.md D1""#,
            ),
        ];
        for (outputs, expected) in cases {
            let diagnostics = generate(&request(CONTRACT, false, outputs)).unwrap_err();
            assert_eq!(diagnostics.as_slice().len(), 1);
            assert_eq!(diagnostics.as_slice()[0].code(), "BXG0039");
            assert_eq!(diagnostics.to_string(), expected);
        }
    }

    #[test]
    fn generator_inventory_duplicates_fail_closed() {
        let request = request(CONTRACT, false, OUTPUTS.to_vec());
        let diagnostics = request
            .require_exact_outputs(&[OUTPUTS[0], OUTPUTS[1], OUTPUTS[1]])
            .unwrap_err();
        assert_eq!(diagnostics.as_slice()[0].code(), "BXG0039");
    }
}
