[package]
name = "boxology-generator-writer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
description = "Filesystem publication"
publish = true

[dependencies]
boxology-generator = { version = "=0.2.0", path = "../boxology-generator" }
boxology-manifest = { version = "=0.2.0", path = "../boxology-manifest" }

[dev-dependencies]
boxology-contract = { version = "=0.2.0", path = "../boxology-contract" }
boxology-generator-model = { version = "=0.2.0", path = "../boxology-generator-model" }
