[package]
name = "xtask"
version = "0.0.0"
edition.workspace = true
publish = false

[dependencies]
boxology-contract = { version = "=0.0.0", path = "../boxology-contract" }
boxology-generator = { version = "=0.0.0", path = "../boxology-generator" }
boxology-generator-model = { version = "=0.0.0", path = "../boxology-generator-model" }
boxology-init = { version = "=0.0.0", path = "../boxology-init" }
boxology-manifest = { version = "=0.0.0", path = "../boxology-manifest" }
boxology-workspace = { version = "=0.0.0", path = "../boxology-workspace" }
sha2 = "=0.10.9"
serde_json = "=1.0.150"
