use super::*;
#[rustfmt::skip]
use boxology_contract::{BoxId, CallContext, Caller, CancelToken, CapabilityId, Deadline, ErasedCallError, ErasedCallTarget, ExposureLevel, OpaquePayload, OpaqueTree, SlotValue, TraceContext};
#[rustfmt::skip]
use boxology_runtime::{AssemblyError, Composition, CompositionBuilder, ImportTarget, RemoteImportTarget, TransportExposure, test_support::StubTransport};
#[rustfmt::skip]
use std::{collections::VecDeque,future::Future, pin::{Pin,pin}, sync::{Arc,Mutex,atomic::{AtomicUsize,Ordering}}, task::{Context,Poll,Waker},time::{Duration,Instant}};
use tokio::sync::Notify;

#[rustfmt::skip]
fn context() -> CallContext { CallContext::new(Caller::Anonymous,None,CancelToken::new(),TraceContext::empty(),None) }
#[rustfmt::skip]
fn ready<F:Future>(future:F)->F::Output { let mut future=pin!(future); match future.as_mut().poll(&mut Context::from_waker(Waker::noop())) { Poll::Ready(v)=>v, Poll::Pending=>panic!("pending") } }
#[rustfmt::skip]
struct Exposure(Vec<TransportExposure>);
#[rustfmt::skip]
impl ErasedCallTarget for Exposure { fn call<'a>(&'a self,id:&'a CapabilityId,ctx:CallContext,input:SlotValue)->Pin<Box<dyn Future<Output=Result<SlotValue,ErasedCallError>>+Send+'a>> { self.0.iter().find(|v|v.descriptor().id()==id).unwrap().dispatch(ctx,input) } }
#[rustfmt::skip]
#[derive(Clone)] struct Remote<T>{inner:T, ids:Arc<Vec<CapabilityId>>}
#[rustfmt::skip]
impl<T:ErasedCallTarget+Send+Sync> ErasedCallTarget for Remote<T>{fn call<'a>(&'a self,id:&'a CapabilityId,ctx:CallContext,input:SlotValue)->Pin<Box<dyn Future<Output=Result<SlotValue,ErasedCallError>>+Send+'a>>{self.inner.call(id,ctx,input)}}
#[rustfmt::skip]
impl<T:ErasedCallTarget+Send+Sync> RemoteImportTarget for Remote<T>{fn supports_capability(&self,id:&CapabilityId)->bool{self.ids.contains(id)}}
#[rustfmt::skip]
fn remote<T:ErasedCallTarget+Send+Sync+'static>(inner:T, descriptor:&'static boxology_contract::ContractDescriptor)->ImportTarget { ImportTarget::remote(Arc::new(Remote{inner,ids:Arc::new(descriptor.capabilities().iter().map(|v|v.id().clone()).collect())})) }
#[rustfmt::skip]
fn request()->RunTurnRequest { RunTurnRequest { session_id:"session".into(),turn_id:"turn-1".into(),user_message:"read it".into(),system_prompt:"be exact".into(),tools:vec![ModelTool{name:"read".into(),description:"Read".into(),input_schema_json:r#"{"type":"object"}"#.into()}],max_output_tokens:Some(64) } }

#[rustfmt::skip]
fn assembled_with_hold(events:Arc<Mutex<Vec<session::SessionEvent>>>, trace:Arc<Mutex<Vec<String>>>, models:Arc<AtomicUsize>, tools:Arc<AtomicUsize>, ambiguous:bool,bad_load_at:usize,hold:Option<(Arc<Notify>,Arc<Notify>)>)->(Composition,boxology_generated_contract::AgentLoopHandle){
    use boxology_import_model_completion::test_support::ModelCompletionFake;
    use boxology_import_session_store::test_support::SessionStoreFake;
    use boxology_import_tool_runner::test_support::ToolRunnerFake;
    let session_events=events.clone(); let load_trace=trace.clone();let load_calls=Arc::new(AtomicUsize::new(0));
    let sessions=SessionStoreFake::new().with_load(move|_,_|{let events=session_events.lock().unwrap().clone();let load=load_calls.fetch_add(1,Ordering::SeqCst)+1;let hold=hold.clone();load_trace.lock().unwrap().push("load".into());async move{if load==1&&let Some((entered,release))=hold{entered.notify_one();release.notified().await}Ok(session::LoadOutcome{result:Some(session::LoadResult{next_sequence:events.len() as u64,events}),failure:(bad_load_at==load).then(||session::SessionFailure{class:session::SessionFailureClass::Local,code:"bad".into(),message:"bad".into(),retryable:false,side_effect_possible:false})})}})
        .with_append({let events=events.clone();let trace=trace.clone();move|_,request|{let mut events=events.lock().unwrap();trace.lock().unwrap().push(format!("append:{}",request.event.event_id));let sequence=request.expected_sequence;let appended=if let Some(old)=events.iter().find(|v|v.event_id==request.event.event_id){assert_eq!((old.sequence,old.payload_json.as_str()),(sequence,request.event.payload_json.as_str()));false}else{assert_eq!(sequence,events.len() as u64);events.push(session::SessionEvent{sequence,event_id:request.event.event_id,kind:request.event.kind,payload_json:request.event.payload_json});true};async move{if ambiguous&&appended{Ok(session::AppendOutcome{result:None,failure:Some(session::SessionFailure{class:session::SessionFailureClass::Local,code:"local_io".into(),message:"local io".into(),retryable:false,side_effect_possible:true})})}else{Ok(session::AppendOutcome{result:Some(session::AppendResult{sequence,appended}),failure:None})}}}});
    let model_trace=trace.clone();let model_calls=models.clone();let model=ModelCompletionFake::new().with_complete(move|_,request|{let n=model_calls.fetch_add(1,Ordering::SeqCst);model_trace.lock().unwrap().push(format!("model:{n}"));async move{if matches!(request.messages.last().unwrap().role,model::MessageRole::Tool){Ok(model::CompletionOutcome{completion:Some(model::CompletionResult{content:Some("done".into()),tool_calls:vec![],finish_reason:model::FinishReason::Stop,usage:model::TokenUsage{input_tokens:4,output_tokens:2,total_tokens:6}}),failure:None})}else{assert!(matches!(request.messages[0].role,model::MessageRole::System));assert!(matches!(request.messages.last().unwrap().role,model::MessageRole::User));Ok(model::CompletionOutcome{completion:Some(model::CompletionResult{content:None,tool_calls:vec![model::ToolCall{id:"call-1".into(),name:"read".into(),arguments_json:r#"{"path":"note.txt"}"#.into()}],finish_reason:model::FinishReason::ToolCalls,usage:model::TokenUsage{input_tokens:2,output_tokens:1,total_tokens:3}}),failure:None})}}});
    let tool_trace=trace.clone();let tool_calls=tools.clone();let tool=ToolRunnerFake::new().with_execute(move|_,request|{tool_calls.fetch_add(1,Ordering::SeqCst);tool_trace.lock().unwrap().push("tool".into());assert_eq!(request.read.unwrap().path,"note.txt");async move{Ok(tool::ExecuteOutcome{result:Some(tool::ExecuteResult{file:Some(tool::FileResult{operation:tool::FileOperation::Read,path:"note.txt".into(),content:Some("hello".into()),bytes:5,changed:false}),bash:None}),failure:None})}});
    let descriptor=generated::implementation_descriptor();let capabilities:Vec<_>=descriptor.contract().capabilities().iter().map(|v|v.id().clone()).collect();let transport=Arc::new(StubTransport::new());let mut builder=CompositionBuilder::new();
    builder.add_box(descriptor,|imports|{let deps=generated::typed_imports(&imports);generated::factory(AgentLoopService::new(deps.model_completion,deps.tool_runner,deps.session_store),imports)});
    let consumer=BoxId::new("agent-loop").unwrap();builder.resolve_import(consumer.clone(),BoxId::new("model-completion").unwrap(),remote(model,model::contract_descriptor()));builder.resolve_import(consumer.clone(),BoxId::new("tool-runner").unwrap(),remote(tool,tool::contract_descriptor()));builder.resolve_import(consumer.clone(),BoxId::new("session-store").unwrap(),remote(sessions,session::contract_descriptor()));for capability in capabilities{builder.expose(consumer.clone(),capability,transport.clone(),ExposureLevel::CodeOnly);}
    let composition=builder.start().unwrap();let handle=boxology_generated_contract::AgentLoopHandle::from_erased(Arc::new(Exposure(transport.runtime().unwrap().exposures().to_vec())));(composition,handle)
}

#[rustfmt::skip]
fn assembled(events:Arc<Mutex<Vec<session::SessionEvent>>>,trace:Arc<Mutex<Vec<String>>>,models:Arc<AtomicUsize>,tools:Arc<AtomicUsize>,ambiguous:bool,bad_load_at:usize)->(Composition,boxology_generated_contract::AgentLoopHandle){assembled_with_hold(events,trace,models,tools,ambiguous,bad_load_at,None)}

#[test]
#[rustfmt::skip]
fn mandatory_three_imports_fail_closed(){let mut builder=CompositionBuilder::new();builder.add_box(generated::implementation_descriptor(),|imports|{let deps=generated::typed_imports(&imports);generated::factory(AgentLoopService::new(deps.model_completion,deps.tool_runner,deps.session_store),imports)});let errors=builder.validate().unwrap_err();assert_eq!(errors.errors().len(),3);assert!(errors.errors().iter().all(|v|matches!(v,AssemblyError::MissingImportResolution{..})));}

#[test]
#[rustfmt::skip]
fn generated_handle_runs_exact_one_tool_trace_and_replays_complete_turn(){let events=Arc::new(Mutex::new(Vec::new()));let trace=Arc::new(Mutex::new(Vec::new()));let models=Arc::new(AtomicUsize::new(0));let tools=Arc::new(AtomicUsize::new(0));let (_composition,handle)=assembled(events.clone(),trace.clone(),models.clone(),tools.clone(),false,0);let result=ready(handle.run_turn(context(),request())).unwrap().result.unwrap();assert_eq!((result.answer.as_str(),result.tool_name.as_deref(),result.usage.total_tokens),("done",Some("read"),9));assert_eq!(*trace.lock().unwrap(),["load","append:turn-1.user","model:0","append:turn-1.call","tool","append:turn-1.result","model:1","append:turn-1.assistant"]);let saved=events.lock().unwrap().clone();assert_eq!(saved.iter().map(|v|v.sequence).collect::<Vec<_>>(),[0,1,2,3]);assert_eq!(serde_json::from_str::<Value>(&saved[0].payload_json).unwrap(),json!({"schema":"agent-loop-event@1","content":"read it"}));drop(handle);trace.lock().unwrap().clear();let (_fresh,replayed)=assembled(events,trace.clone(),models.clone(),tools.clone(),false,0);let replay=ready(replayed.run_turn(context(),request())).unwrap().result.unwrap();assert_eq!(replay.answer,"done");assert_eq!(*trace.lock().unwrap(),["load"]);assert_eq!((models.load(Ordering::SeqCst),tools.load(Ordering::SeqCst)),(2,1));}

#[rustfmt::skip]
fn event(sequence:u64,id:&str,kind:session::SessionEventKind,payload:Value)->session::SessionEvent{session::SessionEvent{sequence,event_id:id.into(),kind,payload_json:serde_json::to_string(&payload).unwrap()}}

#[test]
#[rustfmt::skip]
fn crash_prefixes_resume_only_after_recorded_tool_result(){let user=event(0,"turn-1.user",session::SessionEventKind::User,json!({"schema":"agent-loop-event@1","content":"read it"}));let call=event(1,"turn-1.call",session::SessionEventKind::ToolCall,json!({"schema":"agent-loop-event@1","tool_call_id":"call-1","name":"read","arguments_json":"{\"path\":\"note.txt\"}"}));let events=Arc::new(Mutex::new(vec![user,call]));let trace=Arc::new(Mutex::new(Vec::new()));let models=Arc::new(AtomicUsize::new(0));let tools=Arc::new(AtomicUsize::new(0));let (_c,handle)=assembled(events.clone(),trace.clone(),models.clone(),tools.clone(),false,0);let failure=ready(handle.run_turn(context(),request())).unwrap().failure.unwrap();assert_eq!(failure.code,"incomplete_tool_effect");assert_eq!((models.load(Ordering::SeqCst),tools.load(Ordering::SeqCst)),(0,0));events.lock().unwrap().push(event(2,"turn-1.result",session::SessionEventKind::ToolResult,json!({"schema":"agent-loop-event@1","tool_call_id":"call-1","name":"read","output_json":"{}"})));trace.lock().unwrap().clear();let (_fresh,resumed)=assembled(events.clone(),trace.clone(),models.clone(),tools.clone(),false,0);assert_eq!(ready(resumed.run_turn(context(),request())).unwrap().result.unwrap().answer,"done");assert_eq!((models.load(Ordering::SeqCst),tools.load(Ordering::SeqCst)),(1,0));assert_eq!(events.lock().unwrap().len(),4);}

#[test]
#[rustfmt::skip]
fn ambiguous_appends_reload_and_accept_exact_persisted_events(){let events=Arc::new(Mutex::new(Vec::new()));let trace=Arc::new(Mutex::new(Vec::new()));let (_c,handle)=assembled(events.clone(),trace.clone(),Arc::new(AtomicUsize::new(0)),Arc::new(AtomicUsize::new(0)),true,0);assert_eq!(ready(handle.run_turn(context(),request())).unwrap().result.unwrap().answer,"done");assert_eq!(events.lock().unwrap().len(),4);assert_eq!(trace.lock().unwrap().iter().filter(|v|v.as_str()=="load").count(),5);}

#[tokio::test]
#[rustfmt::skip]
async fn concurrent_same_turn_executes_tool_once_and_replays(){let events=Arc::new(Mutex::new(Vec::new()));let trace=Arc::new(Mutex::new(Vec::new()));let models=Arc::new(AtomicUsize::new(0));let tools=Arc::new(AtomicUsize::new(0));let entered=Arc::new(Notify::new());let release=Arc::new(Notify::new());let (_c,handle)=assembled_with_hold(events.clone(),trace.clone(),models.clone(),tools.clone(),false,0,Some((entered.clone(),release.clone())));let first=tokio::spawn({let handle=handle.clone();async move{handle.run_turn(context(),request()).await}});entered.notified().await;let second=tokio::spawn(async move{handle.run_turn(context(),request()).await});tokio::task::yield_now().await;assert_eq!(*trace.lock().unwrap(),["load"]);release.notify_one();assert_eq!(first.await.unwrap().unwrap().result.unwrap().answer,"done");assert_eq!(second.await.unwrap().unwrap().result.unwrap().answer,"done");assert_eq!((models.load(Ordering::SeqCst),tools.load(Ordering::SeqCst),events.lock().unwrap().len()),(2,1,4));}

#[tokio::test]
#[rustfmt::skip]
async fn queued_cancellation_returns_without_imports(){let trace=Arc::new(Mutex::new(Vec::new()));let entered=Arc::new(Notify::new());let release=Arc::new(Notify::new());let(_c,handle)=assembled_with_hold(Arc::new(Mutex::new(Vec::new())),trace.clone(),Arc::new(AtomicUsize::new(0)),Arc::new(AtomicUsize::new(0)),false,0,Some((entered.clone(),release.clone())));let first=tokio::spawn({let handle=handle.clone();async move{handle.run_turn(context(),request()).await}});entered.notified().await;let token=CancelToken::new();let queued_context=CallContext::new(Caller::Anonymous,None,token.clone(),TraceContext::empty(),None);let queued=tokio::spawn(async move{handle.run_turn(queued_context,request()).await});tokio::task::yield_now().await;assert_eq!(*trace.lock().unwrap(),["load"]);token.cancel();let failure=queued.await.unwrap().unwrap().failure.unwrap();assert!(matches!(failure.class,TurnFailureClass::Cancelled));assert_eq!(*trace.lock().unwrap(),["load"]);release.notify_one();assert!(first.await.unwrap().unwrap().result.is_some());}

#[test]
#[rustfmt::skip]
fn malformed_loads_are_internal_and_do_not_continue(){let malformed=Arc::new(Mutex::new(vec![event(1,"turn-1.user",session::SessionEventKind::User,json!({"schema":"agent-loop-event@1","content":"read it"}))]));for(events,bad_at)in[(malformed,0),(Arc::new(Mutex::new(Vec::new())),1)]{let trace=Arc::new(Mutex::new(Vec::new()));let models=Arc::new(AtomicUsize::new(0));let tools=Arc::new(AtomicUsize::new(0));let(_c,handle)=assembled(events,trace,models.clone(),tools.clone(),false,bad_at);assert!(matches!(ready(handle.run_turn(context(),request())),Err(boxology_contract::CallError::Domain(RunTurnError::Internal))));assert_eq!((models.load(Ordering::SeqCst),tools.load(Ordering::SeqCst)),(0,0));}}

#[test]
#[rustfmt::skip]
fn ambiguous_reload_result_and_failure_is_internal(){let models=Arc::new(AtomicUsize::new(0));let tools=Arc::new(AtomicUsize::new(0));let(_c,handle)=assembled(Arc::new(Mutex::new(Vec::new())),Arc::new(Mutex::new(Vec::new())),models.clone(),tools.clone(),true,2);assert!(matches!(ready(handle.run_turn(context(),request())),Err(boxology_contract::CallError::Domain(RunTurnError::Internal))));assert_eq!((models.load(Ordering::SeqCst),tools.load(Ordering::SeqCst)),(0,0));}

#[test]
#[rustfmt::skip]
fn oversized_schema_is_typed_input_before_imports(){let trace=Arc::new(Mutex::new(Vec::new()));let(_c,handle)=assembled(Arc::new(Mutex::new(Vec::new())),trace.clone(),Arc::new(AtomicUsize::new(0)),Arc::new(AtomicUsize::new(0)),false,0);let mut input=request();input.tools[0].input_schema_json=format!("{{\"x\":\"{}\"}}","a".repeat(TEXT));let failure=ready(handle.run_turn(context(),input)).unwrap().failure.unwrap();assert!(matches!(failure.class,TurnFailureClass::Input));assert!(trace.lock().unwrap().is_empty());}

#[test]
#[rustfmt::skip]
fn maximum_turn_id_produces_valid_event_ids(){let events=Arc::new(Mutex::new(Vec::new()));let(_c,handle)=assembled(events.clone(),Arc::new(Mutex::new(Vec::new())),Arc::new(AtomicUsize::new(0)),Arc::new(AtomicUsize::new(0)),false,0);let mut input=request();input.turn_id="a".repeat(64);input.session_id="s".repeat(64);assert!(ready(handle.run_turn(context(),input)).unwrap().result.is_some());assert!(events.lock().unwrap().iter().all(|event|event.event_id.len()<=128));}

#[derive(Clone)]
struct Evidence {
    events: Arc<Mutex<Vec<session::SessionEvent>>>,
    trace: Arc<Mutex<Vec<String>>>,
    models: Arc<Mutex<Vec<model::CompletionRequest>>>,
    tools: Arc<Mutex<Vec<tool::ExecuteRequest>>>,
}
#[rustfmt::skip]
fn scripted(model_outcomes:Vec<model::CompletionOutcome>,tool_outcome:tool::ExecuteOutcome,initial:Vec<session::SessionEvent>,load_failure:Option<session::SessionFailure>,conflict:u8)->(Composition,boxology_generated_contract::AgentLoopHandle,Evidence){
    use boxology_import_model_completion::test_support::ModelCompletionFake;use boxology_import_session_store::test_support::SessionStoreFake;use boxology_import_tool_runner::test_support::ToolRunnerFake;
    let evidence=Evidence{events:Arc::new(Mutex::new(initial)),trace:Arc::new(Mutex::new(Vec::new())),models:Arc::new(Mutex::new(Vec::new())),tools:Arc::new(Mutex::new(Vec::new()))};let queue=Arc::new(Mutex::new(VecDeque::from(model_outcomes)));let loads=Arc::new(AtomicUsize::new(0));
    let sessions=SessionStoreFake::new().with_load({let e=evidence.clone();move|_,_|{let n=loads.fetch_add(1,Ordering::SeqCst);e.trace.lock().unwrap().push("load".into());let events=e.events.lock().unwrap().clone();let failure=if n==0{load_failure.clone()}else{None};async move{Ok(if let Some(failure)=failure{session::LoadOutcome{result:None,failure:Some(failure)}}else{session::LoadOutcome{result:Some(session::LoadResult{next_sequence:events.len()as u64,events}),failure:None}})}}}).with_append({let e=evidence.clone();move|_,request|{e.trace.lock().unwrap().push(format!("append:{}",request.event.event_id));let mut events=e.events.lock().unwrap();let sequence=request.expected_sequence;let outcome=if conflict==0{events.push(session::SessionEvent{sequence,event_id:request.event.event_id,kind:request.event.kind,payload_json:request.event.payload_json});session::AppendOutcome{result:Some(session::AppendResult{sequence,appended:true}),failure:None}}else{if conflict==2{events.push(session::SessionEvent{sequence,event_id:format!("other-{sequence}"),kind:request.event.kind,payload_json:request.event.payload_json})}session::AppendOutcome{result:None,failure:Some(session_failure(session::SessionFailureClass::Local,"ambiguous",true))}};async move{Ok(outcome)}}});
    let model=ModelCompletionFake::new().with_complete({let e=evidence.clone();move|_,request|{e.trace.lock().unwrap().push("model".into());e.models.lock().unwrap().push(request);let outcome=queue.lock().unwrap().pop_front().unwrap();async move{Ok(outcome)}}});let tool=ToolRunnerFake::new().with_execute({let e=evidence.clone();move|_,request|{e.trace.lock().unwrap().push("tool".into());e.tools.lock().unwrap().push(request);let outcome=tool_outcome.clone();async move{Ok(outcome)}}});
    let descriptor=generated::implementation_descriptor();let capabilities:Vec<_>=descriptor.contract().capabilities().iter().map(|v|v.id().clone()).collect();let transport=Arc::new(StubTransport::new());let mut builder=CompositionBuilder::new();builder.add_box(descriptor,|imports|{let deps=generated::typed_imports(&imports);generated::factory(AgentLoopService::new(deps.model_completion,deps.tool_runner,deps.session_store),imports)});let consumer=BoxId::new("agent-loop").unwrap();builder.resolve_import(consumer.clone(),BoxId::new("model-completion").unwrap(),remote(model,model::contract_descriptor()));builder.resolve_import(consumer.clone(),BoxId::new("tool-runner").unwrap(),remote(tool,tool::contract_descriptor()));builder.resolve_import(consumer.clone(),BoxId::new("session-store").unwrap(),remote(sessions,session::contract_descriptor()));for capability in capabilities{builder.expose(consumer.clone(),capability,transport.clone(),ExposureLevel::CodeOnly);}let composition=builder.start().unwrap();let handle=boxology_generated_contract::AgentLoopHandle::from_erased(Arc::new(Exposure(transport.runtime().unwrap().exposures().to_vec())));(composition,handle,evidence)
}
#[rustfmt::skip] fn call(name:&str,args:String)->model::ToolCall{model::ToolCall{id:"call-1".into(),name:name.into(),arguments_json:args}}
#[rustfmt::skip] fn completion(reason:model::FinishReason,content:Option<String>,calls:Vec<model::ToolCall>)->model::CompletionOutcome{model::CompletionOutcome{completion:Some(model::CompletionResult{content,tool_calls:calls,finish_reason:reason,usage:model::TokenUsage{input_tokens:1,output_tokens:1,total_tokens:2}}),failure:None}}
#[rustfmt::skip] fn first(name:&str,args:&str)->model::CompletionOutcome{completion(model::FinishReason::ToolCalls,None,vec![call(name,args.into())])}
#[rustfmt::skip] fn second()->model::CompletionOutcome{completion(model::FinishReason::Stop,Some("done".into()),vec![])}
#[rustfmt::skip] fn file_result()->tool::ExecuteOutcome{tool::ExecuteOutcome{result:Some(tool::ExecuteResult{file:Some(tool::FileResult{operation:tool::FileOperation::Read,path:"p".into(),content:Some("x".into()),bytes:1,changed:false}),bash:None}),failure:None}}
#[rustfmt::skip] fn file_result_for(name:&str)->tool::ExecuteOutcome{let mut outcome=file_result();outcome.result.as_mut().unwrap().file.as_mut().unwrap().operation=if name=="write"{tool::FileOperation::Write}else{tool::FileOperation::Edit};outcome}
#[rustfmt::skip] fn bash_result()->tool::ExecuteOutcome{tool::ExecuteOutcome{result:Some(tool::ExecuteResult{file:None,bash:Some(tool::BashResult{stdout:"o".into(),stderr:"".into(),stdout_bytes:1,stderr_bytes:0,stdout_truncated:false,stderr_truncated:false,exit_code:Some(0),signal:None})}),failure:None}}
#[rustfmt::skip] fn session_failure(class:session::SessionFailureClass,code:&str,side:bool)->session::SessionFailure{session::SessionFailure{class,code:code.into(),message:code.into(),retryable:false,side_effect_possible:side}}
#[rustfmt::skip] fn tool_failure(class:tool::ToolFailureClass)->tool::ExecuteOutcome{tool::ExecuteOutcome{result:None,failure:Some(tool::ToolFailure{class,code:"tool_failed".into(),message:"failed".into(),retryable:false,side_effect_possible:true})}}
#[rustfmt::skip] fn internal(value:Result<RunTurnOutcome,boxology_contract::CallError<RunTurnError>>)->bool{matches!(value,Err(boxology_contract::CallError::Domain(RunTurnError::Internal)))}

#[test]
#[rustfmt::skip]
fn first_model_malformed_matrix_fails_before_tool_or_call_persistence(){let unknown=model::FinishReason::Unknown{tag:"Future".into(),payload:OpaquePayload::new(OpaqueTree::Null)};let malformed=[model::CompletionOutcome{completion:None,failure:None},model::CompletionOutcome{completion:Some(model::CompletionResult{content:None,tool_calls:vec![],finish_reason:model::FinishReason::ToolCalls,usage:model::TokenUsage{input_tokens:1,output_tokens:1,total_tokens:2}}),failure:Some(model::CompletionFailure{class:model::CompletionFailureClass::Local,code:"x".into(),message:"x".into(),retryable:false,retry_after_seconds:None})}];for outcome in malformed{let(_c,h,e)=scripted(vec![outcome],file_result(),vec![],None,0);assert!(internal(ready(h.run_turn(context(),request()))));assert_eq!((e.events.lock().unwrap().len(),e.tools.lock().unwrap().len()),(1,0));}let mut invalid_id=call("read",r#"{"path":"p"}"#.into());invalid_id.id="".into();let mut cases=vec![completion(model::FinishReason::ToolCalls,Some("text".into()),vec![call("read","{}".into())]),completion(model::FinishReason::ToolCalls,None,vec![]),completion(model::FinishReason::ToolCalls,None,vec![call("read","{}".into()),call("read","{}".into())]),completion(model::FinishReason::Length,None,vec![call("read","{}".into())]),completion(unknown,None,vec![call("read","{}".into())]),completion(model::FinishReason::ToolCalls,None,vec![invalid_id]),first("read","{"),first("read","[]"),first("read",&format!("{{\"path\":\"{}\"}}","x".repeat(LARGE))) ,first("write",r#"{"path":"p","content":"x"}"#)];for outcome in cases.drain(..){let(_c,h,e)=scripted(vec![outcome],file_result(),vec![],None,0);let failure=ready(h.run_turn(context(),request())).unwrap().failure.unwrap();assert!(matches!(failure.class,TurnFailureClass::Protocol));assert_eq!((e.events.lock().unwrap().len(),e.tools.lock().unwrap().len()),(1,0));}}

#[test]
#[rustfmt::skip]
fn second_model_protocol_matrix_stops_after_one_tool(){let cases=[completion(model::FinishReason::ToolCalls,None,vec![call("read","{}".into())]),completion(model::FinishReason::Length,Some("partial".into()),vec![]),completion(model::FinishReason::Stop,Some("".into()),vec![]),completion(model::FinishReason::Stop,Some("mixed".into()),vec![call("read","{}".into())]),completion(model::FinishReason::Stop,Some("x".repeat(LARGE+1)),vec![])];for outcome in cases{let(_c,h,e)=scripted(vec![first("read",r#"{"path":"p"}"#),outcome],file_result(),vec![],None,0);assert!(matches!(ready(h.run_turn(context(),request())).unwrap().failure.unwrap().class,TurnFailureClass::Protocol));assert_eq!((e.events.lock().unwrap().len(),e.tools.lock().unwrap().len()),(3,1));}}

#[test]
#[rustfmt::skip]
fn typed_dependency_failures_and_tool_control_are_truthfully_persisted(){let load=session_failure(session::SessionFailureClass::Local,"load_failed",false);let(_c,h,e)=scripted(vec![],file_result(),vec![],Some(load),0);let failure=ready(h.run_turn(context(),request())).unwrap().failure.unwrap();assert!(matches!(failure.class,TurnFailureClass::Session));assert!(!failure.side_effect_possible);assert!(e.events.lock().unwrap().is_empty());let model_failure=model::CompletionOutcome{completion:None,failure:Some(model::CompletionFailure{class:model::CompletionFailureClass::Transient,code:"model_failed".into(),message:"failed".into(),retryable:true,retry_after_seconds:None})};let(_c,h,e)=scripted(vec![model_failure],file_result(),vec![],None,0);let failure=ready(h.run_turn(context(),request())).unwrap().failure.unwrap();assert!(matches!(failure.class,TurnFailureClass::Model));assert!(failure.side_effect_possible);assert_eq!(e.events.lock().unwrap().len(),1);for(class,expected)in[(tool::ToolFailureClass::Cancelled,TurnFailureClass::Cancelled),(tool::ToolFailureClass::Deadline,TurnFailureClass::Deadline)]{let(_c,h,e)=scripted(vec![first("read",r#"{"path":"p"}"#)],tool_failure(class),vec![],None,0);let failure=ready(h.run_turn(context(),request())).unwrap().failure.unwrap();assert!(std::mem::discriminant(&failure.class)==std::mem::discriminant(&expected));let events=e.events.lock().unwrap();assert_eq!(events.len(),3);assert!(events[2].payload_json.contains("tool_failed"));assert_eq!(e.models.lock().unwrap().len(),1);}let(_c,h,e)=scripted(vec![first("read",r#"{"path":"p"}"#),second()],tool_failure(tool::ToolFailureClass::Local),vec![],None,0);assert!(ready(h.run_turn(context(),request())).unwrap().result.is_some());assert!(e.models.lock().unwrap()[1].messages.last().unwrap().content.as_ref().unwrap().contains("tool_failed"));}

#[test]
#[rustfmt::skip]
fn ambiguous_conflicts_return_original_session_failure_without_continuation(){for conflict in [1,2]{let(_c,h,e)=scripted(vec![],file_result(),vec![],None,conflict);let failure=ready(h.run_turn(context(),request())).unwrap().failure.unwrap();assert!(matches!(failure.class,TurnFailureClass::Session));assert_eq!(failure.code,"ambiguous");assert!(e.models.lock().unwrap().is_empty());assert!(e.tools.lock().unwrap().is_empty());}}

#[test]
#[rustfmt::skip]
fn input_matrix_is_rejected_before_imports(){let mut cases=Vec::new();for value in ["", "bad/id",&"x".repeat(65)]{let mut r=request();r.session_id=value.into();cases.push(r)}for value in ["", "bad/id",&"x".repeat(65)]{let mut r=request();r.turn_id=value.into();cases.push(r)}let mut r=request();r.max_output_tokens=Some(0);cases.push(r);let mut r=request();r.user_message="".into();cases.push(r);let mut r=request();r.user_message="x".repeat(TEXT+1);cases.push(r);let mut r=request();r.system_prompt="x".repeat(TEXT+1);cases.push(r);let mut r=request();r.tools.clear();cases.push(r);let mut r=request();r.tools=vec![r.tools[0].clone();17];cases.push(r);for(name,description,schema)in[("read","x",r#"{"type":"object"}"#.to_string()),("bad/name","x",r#"{}"#.into()),("nope","x",r#"{}"#.into()),("read",&"x".repeat(8193),r#"{}"#.into()),("read","x","[]".into()),("read","x","{".into()),("read","x",format!("{{\"x\":\"{}\"}}","x".repeat(TEXT)))]{let mut r=request();r.tools=vec![ModelTool{name:name.into(),description:description.into(),input_schema_json:schema}];if name=="read"&&description=="x"&&r.tools[0].input_schema_json.contains("type"){r.tools.push(r.tools[0].clone())}cases.push(r)}for request in cases{let trace=Arc::new(Mutex::new(Vec::new()));let(_c,h)=assembled(Arc::new(Mutex::new(Vec::new())),trace.clone(),Arc::new(AtomicUsize::new(0)),Arc::new(AtomicUsize::new(0)),false,0);assert!(matches!(ready(h.run_turn(context(),request)).unwrap().failure.unwrap().class,TurnFailureClass::Input));assert!(trace.lock().unwrap().is_empty());}}

#[test]
#[rustfmt::skip]
fn write_edit_bash_arguments_cross_generated_tool_import_exactly(){let cases=[("write",r#"{"path":"p","content":"c"}"#,false),("edit",r#"{"path":"p","old_text":"a","new_text":"b"}"#,false),("bash",r#"{"command":"pwd","cwd":"/tmp","timeout_ms":9}"#,true)];for(name,args,bash)in cases{let mut input=request();input.tools[0].name=name.into();let outcome=if bash{bash_result()}else{file_result_for(name)};let(_c,h,e)=scripted(vec![first(name,args),second()],outcome,vec![],None,0);assert!(ready(h.run_turn(context(),input)).unwrap().result.is_some());let request=e.tools.lock().unwrap()[0].clone();match name{"write"=>{let v=request.write.unwrap();assert_eq!((v.path,v.content),("p".into(),"c".into()))},"edit"=>{let v=request.edit.unwrap();assert_eq!((v.path,v.old_text,v.new_text),("p".into(),"a".into(),"b".into()))},"bash"=>{let v=request.bash.unwrap();assert_eq!((v.command,v.cwd,v.timeout_ms),("pwd".into(),Some("/tmp".into()),Some(9)))},_=>unreachable!()}}}

#[test]
#[rustfmt::skip]
fn malformed_history_unknown_enum_and_contradictory_tool_result_fail_closed(){let orphan=vec![event(0,"old.result",session::SessionEventKind::ToolResult,json!({"schema":"agent-loop-event@1","tool_call_id":"c","name":"read","output_json":"{}"}))];let malformed=vec![session::SessionEvent{sequence:0,event_id:"old.user".into(),kind:session::SessionEventKind::User,payload_json:"{".into()}];let unknown=vec![session::SessionEvent{sequence:0,event_id:"old.user".into(),kind:session::SessionEventKind::Unknown{tag:"Future".into(),payload:OpaquePayload::new(OpaqueTree::Null)},payload_json:"{}".into()}];for events in [orphan,malformed]{let(_c,h,e)=scripted(vec![],file_result(),events,None,0);assert!(matches!(ready(h.run_turn(context(),request())).unwrap().failure.unwrap().class,TurnFailureClass::Protocol));assert!(e.models.lock().unwrap().is_empty());}let(_c,h,_)=scripted(vec![],file_result(),unknown,None,0);assert!(internal(ready(h.run_turn(context(),request()))));let contradictory=tool::ExecuteOutcome{result:file_result().result,failure:tool_failure(tool::ToolFailureClass::Local).failure};let(_c,h,e)=scripted(vec![first("read",r#"{"path":"p"}"#)],contradictory,vec![],None,0);assert!(internal(ready(h.run_turn(context(),request()))));assert_eq!(e.events.lock().unwrap().len(),2);}

#[test]
#[rustfmt::skip]
fn imported_unknowns_operation_mismatch_and_bounded_history_are_fail_closed(){let opaque=||OpaquePayload::new(OpaqueTree::Null);let session_unknown=session_failure(session::SessionFailureClass::Unknown{tag:"Future".into(),payload:opaque()},"x",false);let(_c,h,_)=scripted(vec![],file_result(),vec![],Some(session_unknown),0);assert!(internal(ready(h.run_turn(context(),request()))));let model_unknown=model::CompletionOutcome{completion:None,failure:Some(model::CompletionFailure{class:model::CompletionFailureClass::Unknown{tag:"Future".into(),payload:opaque()},code:"x".into(),message:"x".into(),retryable:false,retry_after_seconds:None})};let(_c,h,_)=scripted(vec![model_unknown],file_result(),vec![],None,0);assert!(internal(ready(h.run_turn(context(),request()))));let tool_unknown=tool_failure(tool::ToolFailureClass::Unknown{tag:"Future".into(),payload:opaque()});let(_c,h,e)=scripted(vec![first("read",r#"{"path":"p"}"#)],tool_unknown,vec![],None,0);assert!(internal(ready(h.run_turn(context(),request()))));assert_eq!(e.events.lock().unwrap().len(),2);let(_c,h,_)=scripted(vec![first("write",r#"{"path":"p","content":"x"}"#)],file_result(),vec![],None,0);let mut input=request();input.tools[0].name="write".into();assert!(internal(ready(h.run_turn(context(),input))));let bad_text=vec![event(0,"old.user",session::SessionEventKind::User,json!({"schema":"agent-loop-event@1","content":""}))];let bad_call=vec![event(0,"old.call",session::SessionEventKind::ToolCall,json!({"schema":"agent-loop-event@1","tool_call_id":"c","name":"bad/name","arguments_json":"[]"}))];let bad_result=vec![event(0,"old.user",session::SessionEventKind::User,json!({"schema":"agent-loop-event@1","content":"u"})),event(1,"old.call",session::SessionEventKind::ToolCall,json!({"schema":"agent-loop-event@1","tool_call_id":"c","name":"read","arguments_json":"{}"})),event(2,"old.result",session::SessionEventKind::ToolResult,json!({"schema":"agent-loop-event@1","tool_call_id":"c","name":"write","output_json":"{}"}))];for events in [bad_text,bad_call,bad_result]{let(_c,h,e)=scripted(vec![],file_result(),events,None,0);assert!(matches!(ready(h.run_turn(context(),request())).unwrap().failure.unwrap().class,TurnFailureClass::Protocol));assert!(e.models.lock().unwrap().is_empty());}}

#[test]
#[rustfmt::skip]
fn reconstructed_calls_and_outer_payload_are_bounded_and_semantic(){let prior=|name:&str,args:&str|vec![event(0,"old.call",session::SessionEventKind::ToolCall,json!({"schema":"agent-loop-event@1","tool_call_id":"c","name":name,"arguments_json":args})),event(1,"old.result",session::SessionEventKind::ToolResult,json!({"schema":"agent-loop-event@1","tool_call_id":"c","name":name,"output_json":"{}"}))];for events in [prior("nope","{}"),prior("read","{}"),vec![session::SessionEvent{sequence:0,event_id:"old.user".into(),kind:session::SessionEventKind::User,payload_json:"x".repeat(LARGE+1)}]]{let(_c,h,e)=scripted(vec![],file_result(),events,None,0);assert!(matches!(ready(h.run_turn(context(),request())).unwrap().failure.unwrap().class,TurnFailureClass::Protocol));assert!(e.models.lock().unwrap().is_empty());assert!(e.tools.lock().unwrap().is_empty());}}

#[test]
#[rustfmt::skip]
fn persisted_wire_boundary_round_trips_and_escape_heavy_input_stops_before_append(){let mut accepted=request();accepted.user_message="a".repeat(TEXT);let(_c,h,e)=scripted(vec![first("read",r#"{"path":"p"}"#),second()],file_result(),vec![],None,0);assert!(ready(h.run_turn(context(),accepted.clone())).unwrap().result.is_some());let saved=e.events.lock().unwrap().clone();assert!(saved.iter().all(|event|event.payload_json.len()<=EVENT_WIRE));let(_fresh,replay,_)=scripted(vec![],file_result(),saved,None,0);assert_eq!(ready(replay.run_turn(context(),accepted)).unwrap().result.unwrap().answer,"done");let mut rejected=request();rejected.user_message="\0".repeat(TEXT);let(_c,h,e)=scripted(vec![],file_result(),vec![],None,0);let failure=ready(h.run_turn(context(),rejected)).unwrap().failure.unwrap();assert_eq!(failure.code,"event_payload_too_large");assert_eq!(*e.trace.lock().unwrap(),["load"]);assert!(e.events.lock().unwrap().is_empty());}

#[tokio::test]
#[rustfmt::skip]
async fn queued_deadline_returns_without_imports(){let trace=Arc::new(Mutex::new(Vec::new()));let entered=Arc::new(Notify::new());let release=Arc::new(Notify::new());let(_c,handle)=assembled_with_hold(Arc::new(Mutex::new(Vec::new())),trace.clone(),Arc::new(AtomicUsize::new(0)),Arc::new(AtomicUsize::new(0)),false,0,Some((entered.clone(),release.clone())));let first=tokio::spawn({let handle=handle.clone();async move{handle.run_turn(context(),request()).await}});entered.notified().await;let deadline=CallContext::new(Caller::Anonymous,Some(Deadline::at(Instant::now()+Duration::from_millis(1))),CancelToken::new(),TraceContext::empty(),None);let failure=handle.run_turn(deadline,request()).await.unwrap().failure.unwrap();assert!(matches!(failure.class,TurnFailureClass::Deadline));assert_eq!(*trace.lock().unwrap(),["load"]);release.notify_one();assert!(first.await.unwrap().unwrap().result.is_some());}

#[rustfmt::skip] fn compact_request()->CompactRequest{CompactRequest{session_id:"session".into(),checkpoint_id:"cp-1".into(),summary:"durable summary".into()}}
#[rustfmt::skip] fn completed_events()->Vec<session::SessionEvent>{vec![event(0,"old.user",session::SessionEventKind::User,json!({"schema":"agent-loop-event@1","content":"old user"})),event(1,"old.call",session::SessionEventKind::ToolCall,json!({"schema":"agent-loop-event@1","tool_call_id":"old-call","name":"read","arguments_json":"{\"path\":\"old\"}"})),event(2,"old.result",session::SessionEventKind::ToolResult,json!({"schema":"agent-loop-event@1","tool_call_id":"old-call","name":"read","output_json":"{}"})),event(3,"old.assistant",session::SessionEventKind::Assistant,json!({"schema":"agent-loop-event@1","content":"old answer"}))]}

#[test]
#[rustfmt::skip]
fn compact_appends_one_checkpoint_replays_idempotently_without_model_or_tool(){let(_c,h,e)=scripted(vec![],file_result(),completed_events(),None,0);let first=ready(h.compact(context(),compact_request())).unwrap().result.unwrap();assert_eq!((first.event_id.as_str(),first.sequence,first.appended),("checkpoint.cp-1",4,true));assert_eq!(*e.trace.lock().unwrap(),["load","append:checkpoint.cp-1"]);assert!(e.models.lock().unwrap().is_empty()&&e.tools.lock().unwrap().is_empty());let saved=e.events.lock().unwrap();assert_eq!(saved.len(),5);assert_eq!(serde_json::from_str::<Value>(&saved[4].payload_json).unwrap(),json!({"schema":"agent-loop-checkpoint@1","checkpoint_id":"cp-1","summary":"durable summary"}));drop(saved);e.trace.lock().unwrap().clear();let replay=ready(h.compact(context(),compact_request())).unwrap().result.unwrap();assert_eq!((replay.sequence,replay.appended),(4,false));assert_eq!(*e.trace.lock().unwrap(),["load"]);}

#[test]
#[rustfmt::skip]
fn fresh_turn_uses_checkpoint_and_post_checkpoint_context_only(){let(_c,h,e)=scripted(vec![],file_result(),completed_events(),None,0);assert!(ready(h.compact(context(),compact_request())).unwrap().result.is_some());let persisted=e.events.lock().unwrap().clone();let(_fresh,h,e)=scripted(vec![first("read",r#"{"path":"new"}"#),second()],file_result(),persisted,None,0);let mut next=request();next.turn_id="turn-2".into();next.user_message="new user".into();assert_eq!(ready(h.run_turn(context(),next)).unwrap().result.unwrap().answer,"done");let messages=&e.models.lock().unwrap()[0].messages;assert_eq!(messages.iter().filter_map(|v|v.content.as_deref()).collect::<Vec<_>>(),["be exact","durable summary","new user"]);assert_eq!(e.tools.lock().unwrap().len(),1);let persisted=e.events.lock().unwrap().clone();let(_newer,h,e)=scripted(vec![first("read",r#"{"path":"newest"}"#),second()],file_result(),persisted,None,0);let mut next=request();next.turn_id="turn-3".into();next.user_message="newest user".into();assert!(ready(h.run_turn(context(),next)).unwrap().result.is_some());let content=e.models.lock().unwrap()[0].messages.iter().filter_map(|v|v.content.clone()).collect::<Vec<_>>();assert!(content.contains(&"durable summary".into())&&content.contains(&"new user".into())&&content.contains(&"newest user".into()));assert!(!content.contains(&"old user".into())&&!content.contains(&"old answer".into()));}

#[test]
#[rustfmt::skip]
fn compact_rejects_incomplete_malformed_and_conflicting_history(){let incomplete=vec![event(0,"old.user",session::SessionEventKind::User,json!({"schema":"agent-loop-event@1","content":"u"}))];let malformed=vec![event(0,"checkpoint.cp-1",session::SessionEventKind::Assistant,json!({"schema":"agent-loop-checkpoint@1","checkpoint_id":"cp-1","summary":"s"}))];for events in [Vec::new(),incomplete,malformed]{let(_c,h,e)=scripted(vec![],file_result(),events,None,0);assert!(ready(h.compact(context(),compact_request())).unwrap().failure.is_some());assert!(e.models.lock().unwrap().is_empty()&&e.tools.lock().unwrap().is_empty());}let mut conflict=completed_events();conflict.push(event(4,"checkpoint.cp-1",session::SessionEventKind::Assistant,json!({"schema":"agent-loop-checkpoint@1","checkpoint_id":"cp-1","summary":"different"})));let(_c,h,e)=scripted(vec![],file_result(),conflict,None,0);assert_eq!(ready(h.compact(context(),compact_request())).unwrap().failure.unwrap().code,"checkpoint_conflict");assert_eq!(*e.trace.lock().unwrap(),["load"]);}

#[test]
#[rustfmt::skip]
fn adjacent_checkpoints_are_invalid_but_separated_generations_reset_context(){let mut adjacent=completed_events();adjacent.push(session::SessionEvent{sequence:4,event_id:"checkpoint.cp-1".into(),kind:session::SessionEventKind::Assistant,payload_json:r#"{"schema":"agent-loop-checkpoint@1","checkpoint_id":"cp-1","summary":"first summary"}"#.into()});adjacent.push(session::SessionEvent{sequence:5,event_id:"checkpoint.cp-2".into(),kind:session::SessionEventKind::Assistant,payload_json:r#"{"schema":"agent-loop-checkpoint@1","checkpoint_id":"cp-2","summary":"second summary"}"#.into()});let(_c,h,e)=scripted(vec![],file_result(),adjacent,None,0);let mut exact=compact_request();exact.summary="first summary".into();assert_eq!(ready(h.compact(context(),exact)).unwrap().failure.unwrap().code,"history_invalid");assert!(e.models.lock().unwrap().is_empty()&&e.tools.lock().unwrap().is_empty());let(_c,h,e)=scripted(vec![],file_result(),completed_events(),None,0);let mut cp1=compact_request();cp1.summary="first summary".into();assert!(ready(h.compact(context(),cp1)).unwrap().result.is_some());let persisted=e.events.lock().unwrap().clone();let(_fresh,h,e)=scripted(vec![first("read",r#"{"path":"between"}"#),second()],file_result(),persisted,None,0);let mut between=request();between.turn_id="between".into();between.user_message="between user".into();assert!(ready(h.run_turn(context(),between)).unwrap().result.is_some());let mut cp2=compact_request();cp2.checkpoint_id="cp-2".into();cp2.summary="second summary".into();assert!(ready(h.compact(context(),cp2)).unwrap().result.is_some());let persisted=e.events.lock().unwrap().clone();let(_newest,h,e)=scripted(vec![first("read",r#"{"path":"new"}"#),second()],file_result(),persisted,None,0);let mut newest=request();newest.turn_id="newest".into();newest.user_message="newest user".into();assert!(ready(h.run_turn(context(),newest)).unwrap().result.is_some());let content=e.models.lock().unwrap()[0].messages.iter().filter_map(|v|v.content.clone()).collect::<Vec<_>>();assert!(content.contains(&"second summary".into())&&content.contains(&"newest user".into()));assert!(!content.contains(&"first summary".into())&&!content.contains(&"between user".into())&&!content.contains(&"old user".into()));assert_eq!(e.tools.lock().unwrap().len(),1);}

#[test]
#[rustfmt::skip]
fn compact_ambiguous_append_requires_exact_reload_evidence(){for conflict in [1,2]{let(_c,h,e)=scripted(vec![],file_result(),completed_events(),None,conflict);let failure=ready(h.compact(context(),compact_request())).unwrap().failure.unwrap();assert_eq!(failure.code,"ambiguous");assert!(failure.side_effect_possible);assert_eq!(*e.trace.lock().unwrap(),["load","append:checkpoint.cp-1","load"]);assert!(e.models.lock().unwrap().is_empty()&&e.tools.lock().unwrap().is_empty());}let events=Arc::new(Mutex::new(completed_events()));let trace=Arc::new(Mutex::new(Vec::new()));let(_c,h)=assembled(events.clone(),trace.clone(),Arc::new(AtomicUsize::new(0)),Arc::new(AtomicUsize::new(0)),true,0);assert!(ready(h.compact(context(),compact_request())).unwrap().result.unwrap().appended);assert_eq!(events.lock().unwrap().len(),5);assert_eq!(trace.lock().unwrap().iter().filter(|v|v.as_str()=="load").count(),2);}

#[test]
#[rustfmt::skip]
fn compact_input_and_control_bounds_stop_before_append(){let mut cases=Vec::new();for value in ["","bad/id",&"x".repeat(65)]{let mut r=compact_request();r.session_id=value.into();cases.push(r);let mut r=compact_request();r.checkpoint_id=value.into();cases.push(r)}let mut r=compact_request();r.summary="".into();cases.push(r);let mut r=compact_request();r.summary="x".repeat(TEXT+1);cases.push(r);for request in cases{let(_c,h,e)=scripted(vec![],file_result(),completed_events(),None,0);assert!(matches!(ready(h.compact(context(),request)).unwrap().failure.unwrap().class,TurnFailureClass::Input));assert!(e.trace.lock().unwrap().is_empty());}for context in [CallContext::new(Caller::Anonymous,None,{let token=CancelToken::new();token.cancel();token},TraceContext::empty(),None),CallContext::new(Caller::Anonymous,Some(Deadline::at(Instant::now())),CancelToken::new(),TraceContext::empty(),None)]{let(_c,h,e)=scripted(vec![],file_result(),completed_events(),None,0);let failure=ready(h.compact(context,compact_request())).unwrap().failure.unwrap();assert!(matches!(failure.class,TurnFailureClass::Cancelled|TurnFailureClass::Deadline));assert!(e.trace.lock().unwrap().is_empty());}}

#[tokio::test]
#[rustfmt::skip]
async fn queued_compact_cancellation_does_not_load_or_append(){let events=Arc::new(Mutex::new(completed_events()));let trace=Arc::new(Mutex::new(Vec::new()));let entered=Arc::new(Notify::new());let release=Arc::new(Notify::new());let(_c,h)=assembled_with_hold(events.clone(),trace.clone(),Arc::new(AtomicUsize::new(0)),Arc::new(AtomicUsize::new(0)),false,0,Some((entered.clone(),release.clone())));let holder=tokio::spawn({let h=h.clone();async move{h.run_turn(context(),request()).await}});entered.notified().await;let token=CancelToken::new();let queued_context=CallContext::new(Caller::Anonymous,None,token.clone(),TraceContext::empty(),None);let queued=tokio::spawn(async move{h.compact(queued_context,compact_request()).await});tokio::task::yield_now().await;assert_eq!(*trace.lock().unwrap(),["load"]);token.cancel();assert!(matches!(queued.await.unwrap().unwrap().failure.unwrap().class,TurnFailureClass::Cancelled));assert_eq!(*trace.lock().unwrap(),["load"]);release.notify_one();let _=holder.await.unwrap();assert!(events.lock().unwrap().iter().all(|event|!event.event_id.starts_with("checkpoint.")));}
