[package]
name = "ping-app"
version = "0.0.0"
edition.workspace = true
publish = false

[dependencies]
boxology-contract = { workspace = true }
boxology-http = { workspace = true }
boxology-runtime = { workspace = true, features = ["test-support"] }
ping-implementation = { version = "=0.0.0", path = "../../ping/implementation" }

[dev-dependencies]
boxology-manifest = { workspace = true }
tokio = { workspace = true }
