[package]
name = "boxology-init"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
description = "Project initializer"
publish = true

[[bin]]
name = "boxology-init"
path = "src/main.rs"

[dependencies]
boxology-contract = { version = "=0.2.0", path = "../boxology-contract" }
boxology-generator = { version = "=0.2.0", path = "../boxology-generator" }
boxology-generator-model = { version = "=0.2.0", path = "../boxology-generator-model" }
boxology-workspace = { version = "=0.2.0", path = "../boxology-workspace" }

[dev-dependencies]
boxology-manifest = { version = "=0.2.0", path = "../boxology-manifest" }
