[package]
name = "boxology-init"
version = "0.0.0"
edition.workspace = true
publish = false

[dependencies]
boxology-contract = { version = "=0.0.0", path = "../boxology-contract" }
boxology-generator = { version = "=0.0.0", path = "../boxology-generator" }
boxology-generator-model = { version = "=0.0.0", path = "../boxology-generator-model" }

[dev-dependencies]
boxology-manifest = { version = "=0.0.0", path = "../boxology-manifest" }
