use std::fs;
use std::future::Future;
use std::path::{Path, PathBuf};
use std::pin::{Pin, pin};
use std::sync::Arc;
use std::task::{Context, Poll, Waker};

use boxology_contract::{
    BoxId, CallContext, Caller, CancelToken, CapabilityId, ErasedCallError, ErasedCallTarget,
    ExposureLevel, SlotValue, TraceContext,
};
use boxology_generator::generate;
use boxology_generator_model::GenerationRequest;
use boxology_runtime::{
    CompositionBuilder, ImportTarget, TransportExposure, test_support::StubTransport,
};
use greeter_implementation::{GreeterService, generated as greeter_generated};
use hello_implementation::{HelloService, generated as hello_generated};

const OUTPUTS: [&str; 4] = [
    "generated/contract/Cargo.toml",
    "generated/contract/src/lib.rs",
    "generated/adapter/adapter.rs",
    "generated/schema.json",
];
const GENERATED_PATHS: [&str; 4] = [
    "generated/adapter/adapter.rs",
    "generated/contract/Cargo.toml",
    "generated/contract/src/lib.rs",
    "generated/schema.json",
];
const HELLO_SCHEMA: &str = "hello/generated/schema.json";
const PROVENANCE_ANCHOR: &[u8] = b"  \"provenance\": ";
const PROVENANCE_TOKEN: &[u8] = b"\"@PROVENANCE@\"";

fn assert_hello_schema_path(path: &str) {
    assert_eq!(path, "hello/generated/schema.json");
}

fn assert_generated_inventory(paths: &[&str]) {
    assert_eq!(paths.len(), GENERATED_PATHS.len());
    assert_eq!(paths, GENERATED_PATHS.as_slice());
}

fn request() -> GenerationRequest {
    GenerationRequest::new(
        BoxId::new("greeter").expect("fixture identity is valid"),
        "implementation/src/lib.rs".into(),
        vec![
            (
                "boxology.toml".into(),
                include_bytes!("../../greeter/boxology.toml").to_vec(),
            ),
            (
                "implementation/src/lib.rs".into(),
                include_bytes!("../../greeter/implementation/src/lib.rs").to_vec(),
            ),
            (
                "implementation/src/contract.rs".into(),
                include_bytes!("../../greeter/implementation/src/contract.rs").to_vec(),
            ),
            (
                HELLO_SCHEMA.into(),
                include_bytes!("../../hello/generated/schema.json").to_vec(),
            ),
        ],
        vec![(BoxId::new("hello").unwrap(), HELLO_SCHEMA.into())],
        OUTPUTS.iter().map(|path| (*path).to_owned()).collect(),
    )
    .expect("cold fixture request is valid")
}

fn generated_bytes<'a>(tree: &'a boxology_generator::GeneratedTree, path: &str) -> &'a [u8] {
    let matching: Vec<_> = tree
        .files()
        .iter()
        .filter(|file| file.path() == path)
        .collect();
    let [file] = matching.as_slice() else {
        panic!("generated output {path} must occur exactly once")
    };
    file.bytes()
}

fn occurrence_count(bytes: &[u8], needle: &[u8]) -> usize {
    bytes
        .windows(needle.len())
        .filter(|window| *window == needle)
        .count()
}

fn normalize_rust(bytes: &[u8]) -> Vec<u8> {
    let text = std::str::from_utf8(bytes).expect("generated Rust is UTF-8");
    assert_eq!(
        text.matches("// Generated by boxology-generator ").count(),
        1,
        "Rust output must have exactly one generator header"
    );
    let (header, body) = text
        .split_once('\n')
        .expect("generated Rust has a header line");
    assert!(header.starts_with("// Generated by boxology-generator "));
    format!("// Generated by boxology-generator @PROVENANCE@\n{body}").into_bytes()
}

fn normalize_live_schema(bytes: &[u8]) -> Vec<u8> {
    assert_eq!(occurrence_count(bytes, PROVENANCE_ANCHOR), 1);
    let anchor = bytes
        .windows(PROVENANCE_ANCHOR.len())
        .position(|window| window == PROVENANCE_ANCHOR)
        .expect("schema has one top-level provenance anchor");
    let value_start = anchor + PROVENANCE_ANCHOR.len();
    assert_eq!(bytes[value_start], b'{', "live provenance is an object");

    let mut depth = 0;
    let mut in_string = false;
    let mut escaped = false;
    let mut value_end = None;
    for (offset, byte) in bytes[value_start..].iter().copied().enumerate() {
        if in_string {
            if escaped {
                escaped = false;
            } else if byte == b'\\' {
                escaped = true;
            } else if byte == b'"' {
                in_string = false;
            }
            continue;
        }
        match byte {
            b'"' => in_string = true,
            b'{' | b'[' => depth += 1,
            b'}' | b']' => {
                depth -= 1;
                if depth == 0 {
                    value_end = Some(value_start + offset + 1);
                    break;
                }
            }
            _ => {}
        }
    }
    let value_end = value_end.expect("live provenance object is complete");
    let mut normalized =
        Vec::with_capacity(bytes.len() - (value_end - value_start) + PROVENANCE_TOKEN.len());
    normalized.extend_from_slice(&bytes[..value_start]);
    normalized.extend_from_slice(PROVENANCE_TOKEN);
    normalized.extend_from_slice(&bytes[value_end..]);
    normalized
}

fn assert_checked_in_schema_provenance(bytes: &[u8]) {
    assert_eq!(occurrence_count(bytes, PROVENANCE_ANCHOR), 1);
    assert_eq!(occurrence_count(bytes, PROVENANCE_TOKEN), 1);
    let anchor = bytes
        .windows(PROVENANCE_ANCHOR.len())
        .position(|window| window == PROVENANCE_ANCHOR)
        .unwrap();
    assert!(bytes[anchor + PROVENANCE_ANCHOR.len()..].starts_with(PROVENANCE_TOKEN));
}

fn assert_quality_commands_are_exact() {
    let manifest = include_str!("../../greeter/boxology.toml");
    assert_eq!(manifest.matches("[quality]\n").count(), 1);
    let (_, after_quality) = manifest.split_once("[quality]\n").unwrap();
    let (quality, _) = after_quality.split_once("\n\n[[crates]]").unwrap();
    assert_eq!(
        quality,
        r#"commands = [
    "cargo check -p greeter-contract --all-features",
    "cargo test -p greeter-implementation",
]"#
    );
}

fn checked_in(path: &str) -> &'static [u8] {
    match path {
        "generated/contract/Cargo.toml" => {
            include_bytes!("../../greeter/generated/contract/Cargo.toml")
        }
        "generated/contract/src/lib.rs" => {
            include_bytes!("../../greeter/generated/contract/src/lib.rs")
        }
        "generated/adapter/adapter.rs" => {
            include_bytes!("../../greeter/generated/adapter/adapter.rs")
        }
        "generated/schema.json" => include_bytes!("../../greeter/generated/schema.json"),
        _ => panic!("unknown output {path}"),
    }
}

#[test]
fn greeter_adapter_embeds_the_checked_in_hello_revision_exactly_once() {
    const ANCHOR: &str = "  \"revision\": \"";
    let schema = std::str::from_utf8(include_bytes!("../../hello/generated/schema.json"))
        .expect("checked-in hello schema is UTF-8");
    assert_eq!(schema.matches(ANCHOR).count(), 1);
    let revision = schema
        .split_once(ANCHOR)
        .expect("hello schema has a revision anchor")
        .1
        .split_once('"')
        .expect("hello revision is quoted")
        .0;

    let adapter = std::str::from_utf8(include_bytes!("../../greeter/generated/adapter/adapter.rs"))
        .expect("checked-in greeter adapter is UTF-8");
    assert_eq!(adapter.matches(revision).count(), 1);
}

fn checked_in_files() -> Vec<PathBuf> {
    fn visit(root: &Path, directory: &Path, files: &mut Vec<PathBuf>) {
        for entry in fs::read_dir(directory).expect("generated directory is readable") {
            let path = entry.expect("generated directory entry is readable").path();
            if path.is_dir() {
                visit(root, &path, files);
            } else {
                files.push(path.strip_prefix(root).unwrap().to_owned());
            }
        }
    }

    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../greeter");
    let generated = root.join("generated");
    let mut files = Vec::new();
    visit(&root, &generated, &mut files);
    files.sort();
    files
}

fn context() -> CallContext {
    CallContext::new(
        Caller::Anonymous,
        None,
        CancelToken::new(),
        TraceContext::empty(),
        None,
    )
}

fn run<F: Future>(future: F) -> F::Output {
    let mut future = pin!(future);
    match future
        .as_mut()
        .poll(&mut Context::from_waker(Waker::noop()))
    {
        Poll::Ready(output) => output,
        Poll::Pending => panic!("in-process fixture call unexpectedly pending"),
    }
}

struct ExposureTarget(TransportExposure);

impl ErasedCallTarget for ExposureTarget {
    fn call<'a>(
        &'a self,
        capability: &'a CapabilityId,
        context: CallContext,
        input: SlotValue,
    ) -> Pin<Box<dyn Future<Output = Result<SlotValue, ErasedCallError>> + Send + 'a>> {
        assert_eq!(capability, self.0.descriptor().id());
        self.0.dispatch(context, input)
    }
}

#[test]
fn greeter_generation_is_cold_import_bearing_exact_and_matches_checked_in_tree() {
    assert_quality_commands_are_exact();
    let request = request();
    assert_eq!(request.crate_root().as_str(), "implementation/src/lib.rs");
    assert_eq!(request.inputs().len(), 4, "generated files are not inputs");
    assert_eq!(request.imports().len(), 1);
    let [import] = request.imports() else {
        panic!("greeter must declare exactly one import");
    };
    assert_eq!(import.package().as_str(), "hello");
    assert_hello_schema_path(import.schema_path().as_str());
    let schema_input = request
        .inputs()
        .iter()
        .find(|input| input.path().as_str() == "hello/generated/schema.json")
        .expect("hello schema is a generation input");
    assert_eq!(
        schema_input.bytes(),
        include_bytes!("../../hello/generated/schema.json")
    );

    let generated = generate(request).expect("cold Greeter generation succeeds");
    let generated_paths: Vec<_> = generated.files().iter().map(|file| file.path()).collect();
    assert_generated_inventory(&generated_paths);

    let adapter = generated_bytes(&generated, "generated/adapter/adapter.rs");
    assert_eq!(occurrence_count(adapter, b"ImportDescriptor::new("), 1);
    assert_eq!(occurrence_count(adapter, b"pub hello: HelloImport"), 1);

    let checked_in_paths: Vec<_> = checked_in_files()
        .into_iter()
        .map(|path| path.to_string_lossy().into_owned())
        .collect();
    let expected_checked_in = GENERATED_PATHS.map(str::to_owned);
    assert_eq!(checked_in_paths.len(), GENERATED_PATHS.len());
    assert_eq!(checked_in_paths.as_slice(), expected_checked_in.as_slice());
    for path in OUTPUTS {
        let actual = generated_bytes(&generated, path);
        let expected = checked_in(path);
        match Path::new(path)
            .extension()
            .and_then(|extension| extension.to_str())
        {
            Some("rs") => {
                assert_eq!(normalize_rust(actual), normalize_rust(expected), "{path}")
            }
            Some("json") => {
                assert_checked_in_schema_provenance(expected);
                assert_eq!(normalize_live_schema(actual), expected, "{path}")
            }
            _ => assert_eq!(actual, expected, "{path}"),
        }
    }
}

#[test]
#[should_panic]
fn literal_import_path_guard_rejects_a_valid_but_wrong_path_mutant() {
    assert_hello_schema_path("../hello/generated/schema-v2.json");
}

#[test]
#[should_panic]
fn ordered_inventory_guard_rejects_a_same_length_duplicate_mutant() {
    assert_generated_inventory(&[
        "generated/adapter/adapter.rs",
        "generated/contract/Cargo.toml",
        "generated/contract/src/lib.rs",
        "generated/contract/src/lib.rs",
    ]);
}

#[test]
fn resolved_hello_import_runs_through_the_typed_greeter_surface() {
    let greeter_id = BoxId::new("greeter").unwrap();
    let hello_id = BoxId::new("hello").unwrap();
    let greeter_descriptor = greeter_generated::implementation_descriptor();
    let capability = greeter_descriptor.contract().capabilities()[0].id().clone();
    let transport = Arc::new(StubTransport::new());
    let mut builder = CompositionBuilder::new();

    builder.add_box(hello_generated::implementation_descriptor(), |imports| {
        hello_generated::factory(HelloService, imports)
    });
    builder.add_box(greeter_descriptor, |imports| {
        let typed = greeter_generated::typed_imports(&imports);
        greeter_generated::factory(GreeterService::new(typed.hello), imports)
    });
    builder.resolve_import(
        greeter_id.clone(),
        hello_id.clone(),
        ImportTarget::local(hello_id),
    );
    builder.expose(
        greeter_id,
        capability,
        transport.clone(),
        ExposureLevel::External,
    );

    let composition = builder.start().expect("resolved composition starts");
    let runtime = transport.runtime().expect("stub transport started");
    let [exposure] = runtime.exposures() else {
        panic!("greeter must have exactly one typed exposure")
    };
    let greeter =
        greeter_contract::GreeterHandle::from_erased(Arc::new(ExposureTarget(exposure.clone())));
    let greeting = run(greeter.greet_loudly(context(), "Ada".to_owned()))
        .expect("greeter call succeeds through resolved Hello import");
    assert_eq!(greeting, "HELLO, ADA!");
    drop(composition);
}
