use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};

use boxology_contract::BoxId;
use boxology_generator::generate;
use boxology_generator_model::GenerationRequest;

const OUTPUTS: [&str; 4] = [
    "generated/contract/Cargo.toml",
    "generated/contract/src/lib.rs",
    "generated/adapter/adapter.rs",
    "generated/schema.json",
];
const PROVENANCE_ANCHOR: &[u8] = b"  \"provenance\": ";
const PROVENANCE_TOKEN: &[u8] = b"\"@PROVENANCE@\"";

fn request() -> GenerationRequest {
    GenerationRequest::new(
        BoxId::new("ping").expect("fixture identity is valid"),
        "implementation/src/lib.rs".into(),
        vec![
            (
                "boxology.toml".into(),
                include_bytes!("../../ping/boxology.toml").to_vec(),
            ),
            (
                "implementation/src/lib.rs".into(),
                include_bytes!("../../ping/implementation/src/lib.rs").to_vec(),
            ),
        ],
        vec![],
        OUTPUTS.iter().map(|path| (*path).to_owned()).collect(),
    )
    .expect("cold fixture request is valid")
}

fn generated_bytes<'a>(tree: &'a boxology_generator::GeneratedTree, path: &str) -> &'a [u8] {
    tree.files()
        .iter()
        .find(|file| file.path() == path)
        .unwrap_or_else(|| panic!("missing generated output {path}"))
        .bytes()
}

fn normalize_rust(bytes: &[u8]) -> Vec<u8> {
    let text = std::str::from_utf8(bytes).expect("generated Rust is UTF-8");
    assert_eq!(
        text.matches("// Generated by boxology-generator ").count(),
        1,
        "Rust output must have exactly one generator header"
    );
    let (header, body) = text
        .split_once('\n')
        .expect("generated Rust has a header line");
    assert!(header.starts_with("// Generated by boxology-generator "));
    format!("// Generated by boxology-generator @PROVENANCE@\n{body}").into_bytes()
}

fn occurrence_count(bytes: &[u8], needle: &[u8]) -> usize {
    bytes
        .windows(needle.len())
        .filter(|window| *window == needle)
        .count()
}

fn normalize_live_schema(bytes: &[u8]) -> Vec<u8> {
    assert_eq!(occurrence_count(bytes, PROVENANCE_ANCHOR), 1);
    let anchor = bytes
        .windows(PROVENANCE_ANCHOR.len())
        .position(|window| window == PROVENANCE_ANCHOR)
        .expect("schema has one top-level provenance anchor");
    let value_start = anchor + PROVENANCE_ANCHOR.len();
    assert_eq!(bytes[value_start], b'{', "live provenance is an object");

    let mut depth = 0;
    let mut in_string = false;
    let mut escaped = false;
    let mut value_end = None;
    for (offset, byte) in bytes[value_start..].iter().copied().enumerate() {
        if in_string {
            if escaped {
                escaped = false;
            } else if byte == b'\\' {
                escaped = true;
            } else if byte == b'"' {
                in_string = false;
            }
            continue;
        }
        match byte {
            b'"' => in_string = true,
            b'{' | b'[' => depth += 1,
            b'}' | b']' => {
                depth -= 1;
                if depth == 0 {
                    value_end = Some(value_start + offset + 1);
                    break;
                }
            }
            _ => {}
        }
    }
    let value_end = value_end.expect("live provenance object is complete");
    let mut normalized =
        Vec::with_capacity(bytes.len() - (value_end - value_start) + PROVENANCE_TOKEN.len());
    normalized.extend_from_slice(&bytes[..value_start]);
    normalized.extend_from_slice(PROVENANCE_TOKEN);
    normalized.extend_from_slice(&bytes[value_end..]);
    normalized
}

fn assert_checked_in_schema_provenance(bytes: &[u8]) {
    assert_eq!(occurrence_count(bytes, PROVENANCE_ANCHOR), 1);
    assert_eq!(occurrence_count(bytes, PROVENANCE_TOKEN), 1);
    let anchor = bytes
        .windows(PROVENANCE_ANCHOR.len())
        .position(|window| window == PROVENANCE_ANCHOR)
        .unwrap();
    assert!(bytes[anchor + PROVENANCE_ANCHOR.len()..].starts_with(PROVENANCE_TOKEN));
}

fn assert_quality_commands_are_exact() {
    let manifest = include_str!("../../ping/boxology.toml");
    assert_eq!(manifest.matches("[quality]\n").count(), 1);
    let (_, after_quality) = manifest.split_once("[quality]\n").unwrap();
    let (quality, _) = after_quality.split_once("\n\n[[crates]]").unwrap();
    assert_eq!(
        quality,
        "commands = [\n    \"cargo check -p ping-contract --all-features\",\n    \
         \"cargo test -p ping-implementation\",\n]"
    );
}

fn checked_in(path: &str) -> &'static [u8] {
    match path {
        "generated/contract/Cargo.toml" => {
            include_bytes!("../../ping/generated/contract/Cargo.toml")
        }
        "generated/contract/src/lib.rs" => {
            include_bytes!("../../ping/generated/contract/src/lib.rs")
        }
        "generated/adapter/adapter.rs" => {
            include_bytes!("../../ping/generated/adapter/adapter.rs")
        }
        "generated/schema.json" => include_bytes!("../../ping/generated/schema.json"),
        _ => panic!("unknown output {path}"),
    }
}

fn checked_in_files() -> BTreeSet<PathBuf> {
    fn visit(root: &Path, directory: &Path, files: &mut BTreeSet<PathBuf>) {
        for entry in fs::read_dir(directory).expect("generated directory is readable") {
            let path = entry.expect("generated directory entry is readable").path();
            if path.is_dir() {
                visit(root, &path, files);
            } else {
                files.insert(path.strip_prefix(root).unwrap().to_owned());
            }
        }
    }

    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../ping");
    let generated = root.join("generated");
    let mut files = BTreeSet::new();
    visit(&root, &generated, &mut files);
    files
}

#[test]
fn ping_generation_is_cold_exact_and_matches_the_checked_in_tree() {
    assert_quality_commands_are_exact();
    let request = request();
    assert_eq!(request.crate_root().as_str(), "implementation/src/lib.rs");
    assert_eq!(request.inputs().len(), 2, "generated files are not inputs");
    assert!(request.imports().is_empty());
    let generated = generate(request).expect("cold Ping generation succeeds");
    let generated_paths: BTreeSet<_> = generated
        .files()
        .iter()
        .map(|file| file.path().to_owned())
        .collect();
    let expected_paths: BTreeSet<_> = OUTPUTS.iter().map(|path| (*path).to_owned()).collect();
    assert_eq!(generated_paths, expected_paths);

    let checked_in_paths: BTreeSet<_> = checked_in_files()
        .into_iter()
        .map(|path| path.to_string_lossy().into_owned())
        .collect();
    assert_eq!(checked_in_paths, expected_paths);
    for path in OUTPUTS {
        let actual = generated_bytes(&generated, path);
        let expected = checked_in(path);
        match Path::new(path)
            .extension()
            .and_then(|extension| extension.to_str())
        {
            Some("rs") => {
                assert_eq!(normalize_rust(actual), normalize_rust(expected), "{path}")
            }
            Some("json") => {
                assert_checked_in_schema_provenance(expected);
                assert_eq!(normalize_live_schema(actual), expected, "{path}")
            }
            _ => assert_eq!(actual, expected, "{path}"),
        }
    }
}
