use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};

use boxology_contract::BoxId;
use boxology_generator::generate;
use boxology_generator_model::GenerationRequest;
use serde_json::Value;

const OUTPUTS: [&str; 4] = [
    "generated/contract/Cargo.toml",
    "generated/contract/src/lib.rs",
    "generated/adapter/adapter.rs",
    "generated/schema.json",
];

fn request() -> GenerationRequest {
    GenerationRequest::new(
        BoxId::new("ping").expect("fixture identity is valid"),
        "implementation/src/lib.rs".into(),
        vec![
            (
                "boxology.toml".into(),
                include_bytes!("../../ping/boxology.toml").to_vec(),
            ),
            (
                "implementation/src/lib.rs".into(),
                include_bytes!("../../ping/implementation/src/lib.rs").to_vec(),
            ),
        ],
        vec![],
        OUTPUTS.iter().map(|path| (*path).to_owned()).collect(),
    )
    .expect("cold fixture request is valid")
}

fn generated_bytes<'a>(tree: &'a boxology_generator::GeneratedTree, path: &str) -> &'a [u8] {
    tree.files()
        .iter()
        .find(|file| file.path() == path)
        .unwrap_or_else(|| panic!("missing generated output {path}"))
        .bytes()
}

fn normalize_rust(bytes: &[u8]) -> Vec<u8> {
    let text = std::str::from_utf8(bytes).expect("generated Rust is UTF-8");
    assert_eq!(
        text.matches("// Generated by boxology-generator ").count(),
        1,
        "Rust output must have exactly one generator header"
    );
    let (header, body) = text
        .split_once('\n')
        .expect("generated Rust has a header line");
    assert!(header.starts_with("// Generated by boxology-generator "));
    format!("// Generated by boxology-generator @PROVENANCE@\n{body}").into_bytes()
}

fn normalize_schema(bytes: &[u8]) -> Vec<u8> {
    let mut document: Value = serde_json::from_slice(bytes).expect("schema is JSON");
    let object = document
        .as_object_mut()
        .expect("schema document is an object");
    let provenance = object
        .get_mut("provenance")
        .expect("schema has one top-level provenance field");
    assert!(provenance.is_object() || provenance == &Value::String("@PROVENANCE@".into()));
    *provenance = Value::String("@PROVENANCE@".into());
    let mut normalized = serde_json::to_vec_pretty(&document).expect("schema is serializable");
    normalized.push(b'\n');
    normalized
}

fn checked_in(path: &str) -> &'static [u8] {
    match path {
        "generated/contract/Cargo.toml" => {
            include_bytes!("../../ping/generated/contract/Cargo.toml")
        }
        "generated/contract/src/lib.rs" => {
            include_bytes!("../../ping/generated/contract/src/lib.rs")
        }
        "generated/adapter/adapter.rs" => {
            include_bytes!("../../ping/generated/adapter/adapter.rs")
        }
        "generated/schema.json" => include_bytes!("../../ping/generated/schema.json"),
        _ => panic!("unknown output {path}"),
    }
}

fn checked_in_files() -> BTreeSet<PathBuf> {
    fn visit(root: &Path, directory: &Path, files: &mut BTreeSet<PathBuf>) {
        for entry in fs::read_dir(directory).expect("generated directory is readable") {
            let path = entry.expect("generated directory entry is readable").path();
            if path.is_dir() {
                visit(root, &path, files);
            } else {
                files.insert(path.strip_prefix(root).unwrap().to_owned());
            }
        }
    }

    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../ping");
    let generated = root.join("generated");
    let mut files = BTreeSet::new();
    visit(&root, &generated, &mut files);
    files
}

#[test]
fn ping_generation_is_cold_exact_and_matches_the_checked_in_tree() {
    let request = request();
    assert_eq!(request.crate_root().as_str(), "implementation/src/lib.rs");
    assert_eq!(request.inputs().len(), 2, "generated files are not inputs");
    assert!(request.imports().is_empty());
    let generated = generate(&request).expect("cold Ping generation succeeds");
    let generated_paths: BTreeSet<_> = generated
        .files()
        .iter()
        .map(|file| file.path().to_owned())
        .collect();
    let expected_paths: BTreeSet<_> = OUTPUTS.iter().map(|path| (*path).to_owned()).collect();
    assert_eq!(generated_paths, expected_paths);

    let checked_in_paths: BTreeSet<_> = checked_in_files()
        .into_iter()
        .map(|path| path.to_string_lossy().into_owned())
        .collect();
    assert_eq!(checked_in_paths, expected_paths);
    for path in OUTPUTS {
        let actual = generated_bytes(&generated, path);
        let expected = checked_in(path);
        match Path::new(path)
            .extension()
            .and_then(|extension| extension.to_str())
        {
            Some("rs") => {
                assert_eq!(normalize_rust(actual), normalize_rust(expected), "{path}")
            }
            Some("json") => {
                assert_eq!(
                    normalize_schema(actual),
                    normalize_schema(expected),
                    "{path}"
                )
            }
            _ => assert_eq!(actual, expected, "{path}"),
        }
    }
}
