[workspace]
resolver = "3"
members = ["implementation", "generated/contract"]

[workspace.package]
edition = "2024"

[workspace.dependencies]
boxology = { version = "=0.0.0", path = "../../boxology" }
boxology-contract = { version = "=0.0.0", path = "../../boxology-contract" }
boxology-runtime = { version = "=0.0.0", path = "../../boxology-runtime" }
