[package]
name = "boxology"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
description = "Authoring facade"
publish = true

[dependencies]
boxology-contract = { version = "=0.2.1", path = "../boxology-contract" }
boxology-macros = { version = "=0.2.1", path = "../boxology-macros" }
